/**
 * System check — render Bakin's SKILL.md template into the runtime skill
 * store. Source of truth is the repo's `skill/SKILL.md` for static
 * content; the exec-tools block between markers is generated at sync
 * time as a compact runtime summary.
 *
 * Migrated out of src/core/doctor.ts (#139 C8). Auto-fixable — safe
 * because it creates/overwrites only Bakin's own skill file.
 */
import { existsSync, readFileSync } from 'fs'
import { join } from 'path'

import { getSettings } from '../../../../src/core/settings'
import { getAllExecTools } from '../../../../scripts/lib/registry'
import type { AgentRuntimeAdapter } from '../../../../packages/core/src/adapters/runtime'
import type { HealthCheckResult } from '../../../../packages/core/src/plugin-types'

const EXEC_TOOLS_START = '<!-- bakin:exec-tools:start -->'
const EXEC_TOOLS_END = '<!-- bakin:exec-tools:end -->'

function ok(message: string): HealthCheckResult {
  return { check: 'skill', status: 'ok', message, autoFixable: false }
}
function warn(message: string, autoFixable = false): HealthCheckResult {
  return { check: 'skill', status: 'warn', message, autoFixable }
}
function error(message: string): HealthCheckResult {
  return { check: 'skill', status: 'error', message, autoFixable: false }
}
function fixed(message: string): HealthCheckResult {
  return { check: 'skill', status: 'fixed', message, autoFixable: true }
}

/**
 * Build the exec-tools block body from the current tool registry.
 * Returns the inner content that gets placed between the start/end markers
 * (without the markers themselves). Stable across runs when the registry
 * hasn't changed, so the sync check can compare string equality.
 */
function buildExecToolsBlock(): string {
  const tools = getAllExecTools()
  if (tools.length === 0) {
    return '\n<!-- No exec tools registered -->\n'
  }
  return `
## Live Exec Tools

> Auto-generated by \`bakin doctor\` from the live exec-tool registry.
> ${tools.length} tools are available. Use live discovery for complete schemas:

\`\`\`bash
mcporter list bakin-<agent> --schema
\`\`\`

The Bakin skill intentionally keeps this block compact so routine agent turns do not carry a large, stale tool catalog. Common task, workflow, team, asset, schedule, and health tools are listed above in the static quick reference.

### Discovery Examples

\`\`\`bash
mcporter list bakin-main --schema
mcporter call bakin-main.bakin_exec_health_status
\`\`\`
`
}

/**
 * Render the synced skill file: take the repo template, inject the current
 * exec-tools block between its markers, and return the full file contents.
 * Throws if the template is missing the markers — the template is checked
 * into the repo so missing markers is a bug, not an auto-fix case.
 */
function renderSyncedSkill(templateContent: string): string {
  const startIdx = templateContent.indexOf(EXEC_TOOLS_START)
  const endIdx = templateContent.indexOf(EXEC_TOOLS_END)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`skill/SKILL.md template is missing the ${EXEC_TOOLS_START} / ${EXEC_TOOLS_END} markers`)
  }
  const before = templateContent.slice(0, startIdx + EXEC_TOOLS_START.length)
  const after = templateContent.slice(endIdx)
  return `${before}${buildExecToolsBlock()}${after}`
}

export async function checkAndSyncSkill(projectRoot: string, runtime: AgentRuntimeAdapter): Promise<HealthCheckResult[]> {
  const autoFix = getSettings().doctor.autoFixSkill
  const sourceSkill = join(projectRoot, 'skill', 'SKILL.md')
  if (!existsSync(sourceSkill)) {
    return [error('Bakin skill source not found at skill/SKILL.md')]
  }

  const templateContent = readFileSync(sourceSkill, 'utf-8')
  let renderedContent: string
  try {
    renderedContent = renderSyncedSkill(templateContent)
  } catch (err) {
    return [error(`Failed to render skill template: ${(err as Error).message}`)]
  }

  const installedSkill = await runtime.skills.get('bakin')

  if (!installedSkill?.instructions) {
    if (!autoFix) {
      return [warn('Bakin skill not installed in runtime', true)]
    }
    try {
      await runtime.skills.write({ name: 'bakin', instructions: renderedContent, metadata: { source: 'bakin-doctor' } })
      return [fixed('Bakin skill installed in runtime')]
    } catch (err) {
      return [error(`Failed to install skill: ${err}`)]
    }
  }

  const currentContent = installedSkill.instructions
  if (currentContent === renderedContent) {
    return [ok('Bakin skill is up to date')]
  }

  if (!autoFix) {
    return [warn('Bakin skill is outdated in runtime', true)]
  }

  try {
    await runtime.skills.write({ name: 'bakin', instructions: renderedContent, metadata: { source: 'bakin-doctor' } })
    return [fixed('Bakin skill updated in runtime')]
  } catch (err) {
    return [error(`Failed to update skill: ${err}`)]
  }
}
