/**
 * System check — render Bakin's SKILL.md template into the OpenClaw
 * workspace. Source of truth is the repo's `skill/SKILL.md` for static
 * content; the exec-tools block between markers is generated at sync
 * time from the live tool registry.
 *
 * Migrated out of src/core/doctor.ts (#139 C8). Auto-fixable — safe
 * because it creates/overwrites only Bakin's own skill file.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'fs'
import { join } from 'path'

import { getSettings } from '../../../../src/core/settings'
import { getOpenClawPath } from '../../../../packages/core/src/openclaw-home'
import { getAllExecTools } from '../../../../scripts/lib/registry'
import type { HealthCheckResult } from '../../../../packages/core/src/plugin-types'

const EXEC_TOOLS_START = '<!-- bakin:exec-tools:start -->'
const EXEC_TOOLS_END = '<!-- bakin:exec-tools:end -->'

function ok(message: string): HealthCheckResult {
  return { check: 'skill', status: 'ok', message, autoFixable: false }
}
function warn(message: string, autoFixable = false): HealthCheckResult {
  return { check: 'skill', status: 'warn', message, autoFixable }
}
function error(message: string): HealthCheckResult {
  return { check: 'skill', status: 'error', message, autoFixable: false }
}
function fixed(message: string): HealthCheckResult {
  return { check: 'skill', status: 'fixed', message, autoFixable: true }
}

/**
 * Build the exec-tools block body from the current tool registry.
 * Returns the inner content that gets placed between the start/end markers
 * (without the markers themselves). Stable across runs when the registry
 * hasn't changed, so the sync check can compare string equality.
 */
function buildExecToolsBlock(): string {
  const tools = getAllExecTools()
  if (tools.length === 0) {
    return '\n<!-- No exec tools registered -->\n'
  }
  const toolLines = tools
    .map(t => `| \`${t.name}\` | ${t.description} |`)
    .join('\n')
  return `
## Execution Tools

> Auto-generated by \`bakin doctor\` from the exec-tool registry.
> Source of truth is the template at \`skill/SKILL.md\` plus the runtime registry.
> The repo template's managed block is intentionally empty — this file is rendered on sync.

Use these tools to accomplish actual work — saving files, posting content, generating images, scheduling jobs. Called the same way as MCP tools via mcporter.

| Tool | Purpose |
|------|---------|
${toolLines}

### Quick Reference

\`\`\`bash
# Save a file as a managed asset (handles naming + sidecar automatically)
mcporter call bakin-<agent>.bakin_exec_save_asset taskId=<id> type=<images|text|video|audio|plans|data|other> filePath="<path>" description="<desc>"
# Post to Discord (with optional image/video attachment)
mcporter call bakin-<agent>.bakin_exec_post_discord channel="<name>" content="<msg>" taskId=<id>
# Generate image via Nano Banana
mcporter call bakin-<agent>.bakin_exec_gen_image taskId=<id> prompt="<text>" preset=social-portrait model=flash
# Check workflow gate statuses
mcporter call bakin-<agent>.bakin_exec_check_gates taskId=<id>
# Create a recurring scheduled job (NEVER use openclaw cron directly)
mcporter call bakin-<agent>.bakin_exec_schedule_create name="daily-recipe" schedule="every day at 11am" agentId="chef" taskPrompt="Post a short recipe"
# List all scheduled jobs
mcporter call bakin-<agent>.bakin_exec_schedule_list
\`\`\`
`
}

/**
 * Render the synced skill file: take the repo template, inject the current
 * exec-tools block between its markers, and return the full file contents.
 * Throws if the template is missing the markers — the template is checked
 * into the repo so missing markers is a bug, not an auto-fix case.
 */
function renderSyncedSkill(templateContent: string): string {
  const startIdx = templateContent.indexOf(EXEC_TOOLS_START)
  const endIdx = templateContent.indexOf(EXEC_TOOLS_END)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`skill/SKILL.md template is missing the ${EXEC_TOOLS_START} / ${EXEC_TOOLS_END} markers`)
  }
  const before = templateContent.slice(0, startIdx + EXEC_TOOLS_START.length)
  const after = templateContent.slice(endIdx)
  return `${before}${buildExecToolsBlock()}${after}`
}

export function checkAndSyncSkill(projectRoot: string): HealthCheckResult[] {
  const autoFix = getSettings().doctor.autoFixSkill
  const sourceSkill = join(projectRoot, 'skill', 'SKILL.md')
  if (!existsSync(sourceSkill)) {
    return [error('Bakin skill source not found at skill/SKILL.md')]
  }

  const templateContent = readFileSync(sourceSkill, 'utf-8')
  let renderedContent: string
  try {
    renderedContent = renderSyncedSkill(templateContent)
  } catch (err) {
    return [error(`Failed to render skill template: ${(err as Error).message}`)]
  }

  const workspaceSkillDir = getOpenClawPath('workspace', 'skills', 'bakin')
  const targetSkill = join(workspaceSkillDir, 'SKILL.md')

  if (!existsSync(targetSkill)) {
    if (!autoFix) {
      return [warn('Bakin skill not installed in OpenClaw', true)]
    }
    try {
      mkdirSync(workspaceSkillDir, { recursive: true })
      writeFileSync(targetSkill, renderedContent, 'utf-8')
      writeFileSync(join(workspaceSkillDir, '_meta.json'), JSON.stringify({
        slug: 'bakin',
        version: '1.0.0',
        installedAt: Date.now(),
        source: 'bakin-doctor',
      }, null, 2), 'utf-8')
      return [fixed('Bakin skill installed in OpenClaw workspace')]
    } catch (err) {
      return [error(`Failed to install skill: ${err}`)]
    }
  }

  const currentContent = readFileSync(targetSkill, 'utf-8')
  if (currentContent === renderedContent) {
    return [ok('Bakin skill is up to date')]
  }

  // Safety guard: if the currently-installed copy has more exec tools than
  // the render we just built, it means the caller's tool registry is
  // incomplete — most likely because this is a standalone CLI run that
  // didn't activate plugins. Refuse to overwrite rather than silently
  // truncate the installed file. The server-boot path, which activates all
  // plugins, will render the full set and sync on its next cycle.
  const countTools = (text: string) => (text.match(/\| `bakin_exec_/g) || []).length
  const currentCount = countTools(currentContent)
  const renderedCount = countTools(renderedContent)
  if (renderedCount < currentCount) {
    return [warn(
      `Refusing to sync — rendered tool count (${renderedCount}) is less than installed (${currentCount}). ` +
      `Plugins likely not activated in this process. Restart the server to let the boot-time doctor render the full set.`,
      false,
    )]
  }

  if (!autoFix) {
    return [warn('Bakin skill is outdated in OpenClaw', true)]
  }

  try {
    writeFileSync(targetSkill, renderedContent, 'utf-8')
    const metaPath = join(workspaceSkillDir, '_meta.json')
    let meta: Record<string, unknown> = {}
    if (existsSync(metaPath)) {
      try { meta = JSON.parse(readFileSync(metaPath, 'utf-8')) } catch { /* fresh */ }
    }
    const currentVersion = String(meta.version || '1.0.0')
    const parts = currentVersion.split('.').map(Number)
    parts[2] = (parts[2] || 0) + 1
    meta.version = parts.join('.')
    meta.updatedAt = Date.now()
    meta.source = 'bakin-doctor'
    writeFileSync(metaPath, JSON.stringify(meta, null, 2), 'utf-8')
    return [fixed(`Bakin skill updated to v${meta.version}`)]
  } catch (err) {
    return [error(`Failed to update skill: ${err}`)]
  }
}
