// Re-export from @bakin/core — this file exists for backward compatibility
export type {
  StorageAdapter,
  EventBus,
  NavItem,
  APIRoute,
  UISlotRegistration,
  ContentFile,
  ExecToolResult,
  ExecToolDefinition,
  PluginToolContext,
  SkillDefinition,
  ActivityAPI,
  HookAPI,
  PluginContext,
  BakinPlugin,
  MCPlugin,
  PluginManifest,
  PluginEntry,
  BakinConfig,
  MCConfig,
} from '@bakin/core/plugin-types'
