// Re-export from @bakin/core — this file exists for backward compatibility
export type {
  ApprovalActor,
  StorageAdapter,
  EventBus,
  NavItem,
  APIRoute,
  UISlotRegistration,
  ContentFile,
  ExecToolResult,
  ExecToolDefinition,
  PluginToolContext,
  SettingsField,
  PluginSettingsSchema,
  SkillDefinition,
  ActivityAPI,
  HookAPI,
  PluginContext,
  BakinPlugin,
  MCPlugin,
  PluginManifest,
  PluginEntry,
  BakinConfig,
  MCConfig,
  SearchAPI,
  SearchContentTypeDefinition,
  SearchIndexDefinition,
  SearchSchemaField,
  SearchQueryParams,
  SearchResult,
  SearchResponse,
  SearchTransformOp,
  FilePatternMapper,
  FileBackedContentTypeDefinition,
} from '@bakin/core/plugin-types'
