/**
 * `@makinbakin/sdk/patterns` — reusable application-aware UI patterns.
 *
 * Recipes own page hierarchy, responsive composition, and state slots while
 * consumers retain domain data, URL state, and routing behavior.
 */
export {
  ConversationPage,
  ConversationPageBody,
  ConversationPageComposer,
  ConversationPageTimeline,
  DashboardPage,
  DashboardPageContent,
  DetailPage,
  DetailPageAside,
  DetailPageBody,
  DetailPageMain,
  InspectorPanel,
  InspectorPanelContent,
  InspectorPanelFooter,
  InspectorPanelHeader,
  ListPage,
  ListPageContent,
  ListPageControls,
  PageHeader,
  SettingsPage,
  SettingsPageBody,
  SettingsPageContent,
  SettingsPageNavigation,
} from '@bakin/ui/patterns'
export type {
  ConversationPageBodyProps,
  ConversationPageComposerProps,
  ConversationPageMode,
  ConversationPageProps,
  ConversationPageTimelineProps,
  ConversationPageWidth,
  DashboardPageContentProps,
  DashboardPageProps,
  DashboardPageWidth,
  DetailPageAsideProps,
  DetailPageBodyProps,
  DetailPageLayout,
  DetailPageMainProps,
  DetailPageProps,
  DetailPageWidth,
  InspectorPanelContentProps,
  InspectorPanelFooterProps,
  InspectorPanelHeaderProps,
  InspectorPanelProps,
  ListPageContentProps,
  ListPageControlsProps,
  ListPageProps,
  ListPageWidth,
  PageHeaderProps,
  SettingsPageBodyProps,
  SettingsPageContentProps,
  SettingsPageLayout,
  SettingsPageNavigationProps,
  SettingsPageProps,
  SettingsPageWidth,
} from '@bakin/ui/patterns'
