/** Legacy host bridge for the canonical surface and content primitives. */
export {
  Avatar,
  AvatarBadge,
  AvatarFallback,
  AvatarGroup,
  AvatarGroupCount,
  AvatarImage,
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
  Separator,
  Skeleton,
} from '@bakin/ui'
export type {
  AvatarProps,
  AvatarSize,
  CardProps,
  CardSize,
  CollapsibleContentProps,
  CollapsibleProps,
  CollapsibleTriggerProps,
  LegacyAvatarSize,
  LegacyCardSize,
  SeparatorProps,
  SkeletonProps,
  SkeletonShape,
} from '@bakin/ui'
