import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { APP_VERSION } from '../../packages/core/src/constants'

const repoRoot = new URL('../..', import.meta.url).pathname
const docsRoot = join(repoRoot, 'apps/docs')

function writeStableFile(path: string, contents: string): void {
  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, contents.trimEnd() + '\n', 'utf8')
}

const versionLine = `Docs version: Bakin ${APP_VERSION}`

writeStableFile(
  join(docsRoot, 'src/content/docs/reference/generated/coverage.md'),
  `---
title: Generated Coverage
description: Coverage report for generated Bakin documentation surfaces.
---

# Generated Coverage

${versionLine}

This page is generated by \`scripts/docs/generate.ts\`.

The current scaffold establishes the public coverage contract. The next implementation pass will replace this summary with inventories for CLI commands, HTTP routes, plugin routes, hooks, slots, SDK exports, settings, exec/MCP tools, agent package contracts, snippets, and LLM bundles.

| Surface | Launch requirement | Current status |
| --- | --- | --- |
| CLI commands | Structured registry, examples, docs metadata | Planned |
| HTTP routes | Zod input schemas, examples, visibility, stability | Planned |
| Plugin routes | Same contract as HTTP routes | Planned |
| Hooks | Contract objects, kind, schemas, examples | Planned |
| Slots | Contract objects, props, examples | Planned |
| SDK exports | TypeDoc, TSDoc, stability | Planned |
| Examples | External fixtures, tested or explicitly illustrative | Planned |
| LLM docs | \`/llms.txt\`, \`/llms-full.txt\`, targeted bundles | Active |
`,
)

writeStableFile(
  join(docsRoot, 'public/llms.txt'),
  `# Bakin Docs

${versionLine}

Bakin is a self-hosted dashboard, backend, CLI, and extension system for running agent work with OpenClaw. Use these docs to install Bakin, operate it, build plugins, author agent packages, and understand the public contracts exposed by the SDK, hooks, slots, CLI, and HTTP API.

Primary docs:

- Start: https://docs.makinbakin.com/start/overview/
  Use this to understand what Bakin is and where to begin.

- Install Bakin: https://docs.makinbakin.com/run/install/
  Use this for the released one-line install path and platform notes.

- Run Bakin: https://docs.makinbakin.com/run/operation/
  Use this for lifecycle commands, health checks, updates, and runtime operation.

- Plugin authoring: https://docs.makinbakin.com/extend/plugins/overview/
  Use this when building Bakin plugins with @bakin/sdk.

- Agent authoring: https://docs.makinbakin.com/extend/agents/overview/
  Use this when creating agent packages or writing instructions for coding agents working with Bakin.

- SDK docs: https://docs.makinbakin.com/extend/sdk/overview/
  Use this for @bakin/sdk imports, UI components, hooks, slots, and public extension contracts.

LLM bundles:

- Full context: https://docs.makinbakin.com/llms-full.txt
- Plugin authoring bundle: https://docs.makinbakin.com/llms/plugin-authoring.md
- Agent authoring bundle: https://docs.makinbakin.com/llms/agent-authoring.md
- SDK reference bundle: https://docs.makinbakin.com/llms/sdk-reference.md
- API reference bundle: https://docs.makinbakin.com/llms/api.md
`,
)

writeStableFile(
  join(docsRoot, 'public/llms-full.txt'),
  `# Bakin Full LLM Context

${versionLine}

Audience: coding agents, plugin authors, agent authors, and technical operators.

Canonical docs: https://docs.makinbakin.com/

## Operating Rules

- Use \`Bakin\` for the product and \`bakin\` for the CLI.
- Prefer the released one-line installer for end-user install instructions.
- Use \`@bakin/sdk/*\` imports for plugin-facing code.
- Do not import host internals or another plugin's internals from a plugin.
- Treat public hooks, slots, CLI commands, HTTP routes, settings, and SDK exports as documented contracts.
- Prefer tested docs snippets and generated reference over guessing APIs.

## Useful Bundles

- Plugin authoring: /llms/plugin-authoring.md
- Agent authoring: /llms/agent-authoring.md
- SDK reference: /llms/sdk-reference.md
- API reference: /llms/api.md

## Fetch Examples

\`\`\`sh
curl -fsSL https://docs.makinbakin.com/llms/plugin-authoring.md
curl -fsSL https://docs.makinbakin.com/llms/agent-authoring.md
\`\`\`
`,
)

const bundles = {
  'plugin-authoring.md': {
    title: 'Bakin Plugin Authoring',
    body: 'Use `@bakin/sdk/*` for plugin code. Public plugin examples must be backed by tested snippets. Public hooks, slots, routes, settings, and exec/MCP tools require metadata, schemas, examples, visibility, and stability before launch.',
  },
  'agent-authoring.md': {
    title: 'Bakin Agent Authoring',
    body: 'Agent-facing docs are explicit and labeled. Explain only the OpenClaw concepts needed to use Bakin, then link to OpenClaw for deeper details. Agent package examples must be validated before publication.',
  },
  'sdk-reference.md': {
    title: 'Bakin SDK Reference',
    body: 'The SDK reference is generated from `@bakin/sdk/*` exports with TypeDoc and custom usage pages. Every public SDK export requires TSDoc and stability metadata before launch.',
  },
  'api.md': {
    title: 'Bakin API Reference',
    body: 'HTTP API docs are generated from docs-aware route definitions. Public inputs are validated with Zod at runtime. Structured outputs are validated in tests, docs generation, or development checks where practical.',
  },
}

for (const [file, { title, body }] of Object.entries(bundles)) {
  writeStableFile(
    join(docsRoot, 'public/llms', file),
    `# ${title}

${versionLine}

Audience: coding agents and technical authors.

Canonical docs: https://docs.makinbakin.com/

${body}
`,
  )
}

console.log('Generated docs scaffolding artifacts')
