/**
 * Architecture scan guarding the plugin boundary (audit FW3).
 *
 * Two rules, enforced over import/require specifiers (static `from '…'`,
 * bare `import '…'`, dynamic `import('…')`, and `require('…')` — value AND
 * type imports alike):
 *
 * (a) No file under `plugins/<a>/` imports from `plugins/<b>/` (a ≠ b).
 *     Cross-plugin calls go through the HookRegistry; shared logic lives in
 *     `@bakin/core` or on the SDK surface. The last offenders (images →
 *     assets service/id/manifest, images → workflows load-defaults) were
 *     rewired onto ctx.assets / @makinbakin/sdk/utils /
 *     @bakin/core/workflows/load-defaults in this series.
 *
 * (b) No file under `src/` or `packages/host/src/` imports from `plugins/*`,
 *     except the sanctioned crossings in CORE_TO_PLUGIN_ALLOWLIST below.
 *     Core reaches plugin functionality via AppServices/ctx facades — a new
 *     direct import is a boundary leak, not a convenience.
 *
 * Plugin ids are derived from the `plugins/` directory, so a new plugin is
 * covered automatically; `@bakin/<pluginId>` tsconfig aliases are treated as
 * plugin imports too.
 *
 * Pure scanner: walks the source tree as text, imports no app modules.
 */
import { describe, expect, it } from 'bun:test'
import { readFileSync, readdirSync, statSync } from 'fs'
import { dirname, join, relative, resolve } from 'path'

const ROOT = process.cwd()

/**
 * The ONLY files under src/ or packages/host/src/ allowed to import from
 * plugins/*. Every entry needs a one-line reason; anything else must go
 * through AppServices / PluginContext facades.
 */
const CORE_TO_PLUGIN_ALLOWLIST: Record<string, string> = {
  // The sanctioned static-import table: embeds core plugin server entries +
  // bakin-plugin.json manifests into the single-file binary (#421).
  'src/lib/plugin-static-imports.ts':
    'sanctioned binary embed table for core plugin server code + manifests',
  // The sanctioned assets bridge: the single lazy crossing core/ctx.assets
  // use to reach the versioned asset service (see its header).
  'src/core/assets-bridge.ts':
    'sanctioned assets bridge — the one core-side crossing into the assets plugin',
  // Generated by scripts/generate-embedded-assets.ts: imports core plugins'
  // dist BROWSER assets (client.js/client.css) `with { type: "file" }` so the
  // compiled binary can serve them — asset embeds, not code imports (#421).
  'packages/host/src/api/_embedded-assets-static.ts':
    'generated embedded-asset manifest for plugin dist browser assets',
}

const SKIP_DIRS = new Set(['node_modules', 'dist', '.git'])

function* walk(dir: string): Generator<string> {
  for (const name of readdirSync(dir)) {
    if (SKIP_DIRS.has(name)) continue
    const full = join(dir, name)
    if (statSync(full).isDirectory()) yield* walk(full)
    else if (/\.tsx?$/.test(name) && !/\.test\.tsx?$/.test(name)) yield full
  }
}

function pluginIds(): string[] {
  return readdirSync(join(ROOT, 'plugins')).filter((name) =>
    statSync(join(ROOT, 'plugins', name)).isDirectory(),
  )
}

// Static `from '…'` (imports, re-exports, import type), bare `import '…'`,
// dynamic `import('…')`, and `require('…')`.
const IMPORT_RE = /(?:\bfrom\s*|\bimport\s*\(\s*|\brequire\s*\(\s*|^\s*import\s+)['"]([^'"]+)['"]/gm

/** The plugin a specifier resolves into, or null (non-plugin import). */
function pluginOfSpecifier(file: string, spec: string, ids: Set<string>): string | null {
  const alias = /^@bakin\/([^/]+)(?:\/|$)/.exec(spec)
  if (alias && ids.has(alias[1])) return alias[1]
  if (spec.startsWith('.')) {
    const rel = relative(join(ROOT, 'plugins'), resolve(dirname(file), spec))
    const m = /^([^/.][^/]*)\//.exec(rel + '/')
    if (m && ids.has(m[1])) return m[1]
  }
  return null
}

function pluginImports(file: string, ids: Set<string>): Array<{ spec: string; target: string }> {
  const src = readFileSync(file, 'utf-8')
  const found: Array<{ spec: string; target: string }> = []
  for (const m of src.matchAll(IMPORT_RE)) {
    const target = pluginOfSpecifier(file, m[1], ids)
    if (target) found.push({ spec: m[1], target })
  }
  return found
}

describe('plugin boundaries', () => {
  const ids = new Set(pluginIds())

  it('scans a sane plugin set', () => {
    // If plugins/ ever moves, this scan must fail loudly instead of silently
    // asserting over nothing.
    expect(ids.size).toBeGreaterThanOrEqual(10)
  })

  it('no plugin imports from another plugin', () => {
    const offenders: string[] = []
    for (const id of ids) {
      for (const file of walk(join(ROOT, 'plugins', id))) {
        for (const { spec, target } of pluginImports(file, ids)) {
          if (target !== id) offenders.push(`${relative(ROOT, file)} -> ${spec}`)
        }
      }
    }
    expect(offenders).toEqual([])
  })

  it('core and host import plugins only through the sanctioned crossings', () => {
    const offenders: string[] = []
    const seenAllowed = new Set<string>()
    for (const root of ['src', 'packages/host/src']) {
      for (const file of walk(join(ROOT, root))) {
        const rel = relative(ROOT, file)
        const found = pluginImports(file, ids)
        if (found.length === 0) continue
        if (rel in CORE_TO_PLUGIN_ALLOWLIST) {
          seenAllowed.add(rel)
          continue
        }
        for (const { spec } of found) offenders.push(`${rel} -> ${spec}`)
      }
    }
    expect(offenders).toEqual([])
    // Ratchet: an allowlist entry that no longer crosses the boundary is
    // stale — remove it so the list only ever shrinks.
    const stale = Object.keys(CORE_TO_PLUGIN_ALLOWLIST).filter((f) => !seenAllowed.has(f))
    expect(stale).toEqual([])
  })
})
