// Generated by bun run ui:tokens:generate. Do not edit.
export const BAKIN_SEMANTIC_TOKENS = [
  {
    "name": "semantic.color.action.primary.background",
    "type": "color",
    "cssVariable": "--bakin-color-action-primary-background",
    "cssValue": "#22c55e",
    "tailwindVariable": "--color-bakin-action-primary-background",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/action/primary/background"
  },
  {
    "name": "semantic.color.action.primary.foreground",
    "type": "color",
    "cssVariable": "--bakin-color-action-primary-foreground",
    "cssValue": "#052e16",
    "tailwindVariable": "--color-bakin-action-primary-foreground",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/action/primary/foreground"
  },
  {
    "name": "semantic.color.border.subtle",
    "type": "color",
    "cssVariable": "--bakin-color-border-subtle",
    "cssValue": "#4a4747",
    "tailwindVariable": "--color-bakin-border-subtle",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/border/subtle"
  },
  {
    "name": "semantic.color.canvas.default",
    "type": "color",
    "cssVariable": "--bakin-color-canvas-default",
    "cssValue": "#0f0e0e",
    "tailwindVariable": "--color-bakin-canvas-default",
    "description": "The application canvas.",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/canvas/default"
  },
  {
    "name": "semantic.color.focus.ring",
    "type": "color",
    "cssVariable": "--bakin-color-focus-ring",
    "cssValue": "#22c55e",
    "tailwindVariable": "--color-bakin-focus-ring",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/focus/ring"
  },
  {
    "name": "semantic.color.signal.accent",
    "type": "color",
    "cssVariable": "--bakin-color-signal-accent",
    "cssValue": "#ff007f",
    "tailwindVariable": "--color-bakin-signal-accent",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/signal/accent"
  },
  {
    "name": "semantic.color.signal.danger",
    "type": "color",
    "cssVariable": "--bakin-color-signal-danger",
    "cssValue": "#ef4444",
    "tailwindVariable": "--color-bakin-signal-danger",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/signal/danger"
  },
  {
    "name": "semantic.color.signal.highlight",
    "type": "color",
    "cssVariable": "--bakin-color-signal-highlight",
    "cssValue": "#eaea00",
    "tailwindVariable": "--color-bakin-signal-highlight",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/signal/highlight"
  },
  {
    "name": "semantic.color.surface.default",
    "type": "color",
    "cssVariable": "--bakin-color-surface-default",
    "cssValue": "#151313",
    "tailwindVariable": "--color-bakin-surface-default",
    "description": "The default bounded surface.",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/surface/default"
  },
  {
    "name": "semantic.color.text.muted",
    "type": "color",
    "cssVariable": "--bakin-color-text-muted",
    "cssValue": "#aeaaaa",
    "tailwindVariable": "--color-bakin-text-muted",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/text/muted"
  },
  {
    "name": "semantic.color.text.primary",
    "type": "color",
    "cssVariable": "--bakin-color-text-primary",
    "cssValue": "#ffffff",
    "tailwindVariable": "--color-bakin-text-primary",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/color/text/primary"
  },
  {
    "name": "semantic.layout.space.0",
    "type": "dimension",
    "cssVariable": "--bakin-layout-space-0",
    "cssValue": "0px",
    "tailwindVariable": "--spacing-bakin-0",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/layout/space/0"
  },
  {
    "name": "semantic.layout.space.1",
    "type": "dimension",
    "cssVariable": "--bakin-layout-space-1",
    "cssValue": "0.25rem",
    "tailwindVariable": "--spacing-bakin-1",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/layout/space/1"
  },
  {
    "name": "semantic.layout.space.2",
    "type": "dimension",
    "cssVariable": "--bakin-layout-space-2",
    "cssValue": "0.5rem",
    "tailwindVariable": "--spacing-bakin-2",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/layout/space/2"
  },
  {
    "name": "semantic.layout.space.3",
    "type": "dimension",
    "cssVariable": "--bakin-layout-space-3",
    "cssValue": "0.75rem",
    "tailwindVariable": "--spacing-bakin-3",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/layout/space/3"
  },
  {
    "name": "semantic.layout.space.4",
    "type": "dimension",
    "cssVariable": "--bakin-layout-space-4",
    "cssValue": "1rem",
    "tailwindVariable": "--spacing-bakin-4",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/layout/space/4"
  },
  {
    "name": "semantic.layout.space.6",
    "type": "dimension",
    "cssVariable": "--bakin-layout-space-6",
    "cssValue": "1.5rem",
    "tailwindVariable": "--spacing-bakin-6",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/layout/space/6"
  },
  {
    "name": "semantic.layout.space.8",
    "type": "dimension",
    "cssVariable": "--bakin-layout-space-8",
    "cssValue": "2rem",
    "tailwindVariable": "--spacing-bakin-8",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/layout/space/8"
  },
  {
    "name": "semantic.motion.duration.feedback",
    "type": "duration",
    "cssVariable": "--bakin-motion-duration-feedback",
    "cssValue": "120ms",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/motion/duration/feedback"
  },
  {
    "name": "semantic.motion.duration.instant",
    "type": "duration",
    "cssVariable": "--bakin-motion-duration-instant",
    "cssValue": "0ms",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/motion/duration/instant"
  },
  {
    "name": "semantic.motion.duration.transition",
    "type": "duration",
    "cssVariable": "--bakin-motion-duration-transition",
    "cssValue": "180ms",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/motion/duration/transition"
  },
  {
    "name": "semantic.motion.easing.standard",
    "type": "cubicBezier",
    "cssVariable": "--bakin-motion-easing-standard",
    "cssValue": "cubic-bezier(0.2, 0, 0, 1)",
    "tailwindVariable": "--ease-bakin-standard",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/motion/easing/standard"
  },
  {
    "name": "semantic.radius.control",
    "type": "dimension",
    "cssVariable": "--bakin-radius-control",
    "cssValue": "0.25rem",
    "tailwindVariable": "--radius-bakin-control",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/radius/control"
  },
  {
    "name": "semantic.radius.overlay",
    "type": "dimension",
    "cssVariable": "--bakin-radius-overlay",
    "cssValue": "0.75rem",
    "tailwindVariable": "--radius-bakin-overlay",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/radius/overlay"
  },
  {
    "name": "semantic.radius.pill",
    "type": "dimension",
    "cssVariable": "--bakin-radius-pill",
    "cssValue": "999px",
    "tailwindVariable": "--radius-bakin-pill",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/radius/pill"
  },
  {
    "name": "semantic.radius.surface",
    "type": "dimension",
    "cssVariable": "--bakin-radius-surface",
    "cssValue": "0.5rem",
    "tailwindVariable": "--radius-bakin-surface",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/radius/surface"
  },
  {
    "name": "semantic.state.opacity.disabled",
    "type": "number",
    "cssVariable": "--bakin-state-opacity-disabled",
    "cssValue": "0.48",
    "source": "packages/ui/tokens/semantic.tokens.json#/semantic/state/opacity/disabled"
  }
] as const

export type BakinSemanticTokenName = typeof BAKIN_SEMANTIC_TOKENS[number]['name']
export type BakinSemanticCssVariable = typeof BAKIN_SEMANTIC_TOKENS[number]['cssVariable']
