import { chmodSync, mkdirSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { fileURLToPath } from 'url'
import { getMockHome } from './env'

const __dirname = dirname(fileURLToPath(import.meta.url))

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'\\''`)}'`
}

export function installCliShim(mockHome = getMockHome()): string {
  const binDir = join(mockHome, 'bin')
  mkdirSync(binDir, { recursive: true })

  const shimDest = join(binDir, 'openclaw')
  const shimTarget = join(__dirname, 'cli-shim.ts')
  writeFileSync(shimDest, [
    '#!/usr/bin/env bash',
    '# Generated by Imitation Crab; delegates to the repo-local CLI shim.',
    `exec bun run ${shellQuote(shimTarget)} "$@"`,
    '',
  ].join('\n'), 'utf-8')
  chmodSync(shimDest, 0o755)

  return shimDest
}
