/**
 * GENERATED by scripts/generate-media-pin.ts — do not edit by hand.
 * Regenerate: bun scripts/generate-media-pin.ts --sharp-version <v>
 * Pin-bump runbook: .claude/knowledge/media-pipeline.md
 * Self-contained by design: importing types from ./pin creates an import
 * cycle (check:cycles); ./pin structurally types this object on assignment.
 */
export const SHARP_PIN_DATA = {
  version: '0.34.5',
  shared: [
    { name: 'sharp', version: '0.34.5', url: 'https://registry.npmjs.org/sharp/-/sharp-0.34.5.tgz', sha256: '460712506f9df808cf25bc2ba15be828bfa9179bd31b6ca47a9db624980026c3' },
    { name: 'semver', version: '7.8.5', url: 'https://registry.npmjs.org/semver/-/semver-7.8.5.tgz', sha256: 'd85045d4300d7d57c891336b95df532e73f34c22ffcd222452b6d08b9d127d5d' },
    { name: '@img/colour', version: '1.1.0', url: 'https://registry.npmjs.org/@img/colour/-/colour-1.1.0.tgz', sha256: '6c2df3ac33d4b8647191ad8942a579e6004be00c25846677eab85f04702d85b1' },
    { name: 'detect-libc', version: '2.1.2', url: 'https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz', sha256: '270dec0fc06cff86481da8af2dd8f18dee6b602790b14ef0e1c2c18d7da39427' },
  ],
  platform: {
  'darwin-arm64': [
    { name: '@img/sharp-darwin-arm64', version: '0.34.5', url: 'https://registry.npmjs.org/@img/sharp-darwin-arm64/-/sharp-darwin-arm64-0.34.5.tgz', sha256: '553ed774fa3be2290f1e55eadbd7f8350c06001939107a15810d9d6488bf2fc2' },
    { name: '@img/sharp-libvips-darwin-arm64', version: '1.2.4', url: 'https://registry.npmjs.org/@img/sharp-libvips-darwin-arm64/-/sharp-libvips-darwin-arm64-1.2.4.tgz', sha256: '2b7a106979fc6c3e9ba27a7b9e305c610a0c11c2d10aac3b3d317d706cf302f7' },
  ],
  'linux-x64': [
    { name: '@img/sharp-linux-x64', version: '0.34.5', url: 'https://registry.npmjs.org/@img/sharp-linux-x64/-/sharp-linux-x64-0.34.5.tgz', sha256: 'fe13679b222907d9584214bf837d5d92c9456ba0880fc24625dd118ab7918ef9' },
    { name: '@img/sharp-libvips-linux-x64', version: '1.2.4', url: 'https://registry.npmjs.org/@img/sharp-libvips-linux-x64/-/sharp-libvips-linux-x64-1.2.4.tgz', sha256: '43c132f5a31dc0d38aff8376fdce66b4761118a451e41dfa36f9829d9607c07c' },
  ],
  'linux-arm64': [
    { name: '@img/sharp-linux-arm64', version: '0.34.5', url: 'https://registry.npmjs.org/@img/sharp-linux-arm64/-/sharp-linux-arm64-0.34.5.tgz', sha256: 'a1b6abb82159f8e9700f337ea9fc977892ddf41fbcbcfe168ae047a5cddc70be' },
    { name: '@img/sharp-libvips-linux-arm64', version: '1.2.4', url: 'https://registry.npmjs.org/@img/sharp-libvips-linux-arm64/-/sharp-libvips-linux-arm64-1.2.4.tgz', sha256: 'bbbac2ec3c5e3ba8e8051d92a23887ae40ca30ed37555da5ffe356e58781a56d' },
  ],
  },
}
