/**
 * GENERATED by scripts/generate-media-pin.ts — do not edit by hand.
 * Regenerate: bun scripts/generate-media-pin.ts --sharp-version <v>
 * Pin-bump runbook: .claude/knowledge/media-pipeline.md
 * Self-contained by design: importing types from ./pin creates an import
 * cycle (check:cycles); ./pin structurally types this object on assignment.
 */
export const SHARP_PIN_DATA = {
  version: '0.35.5',
  shared: [
    { name: 'sharp', version: '0.35.5', url: 'https://registry.npmjs.org/sharp/-/sharp-0.35.5.tgz', sha256: '3b6bbbe6b308f5c383938ca4a31926cd5d79c4651ed8c5fda16a97da2014a9ac' },
    { name: 'semver', version: '7.8.5', url: 'https://registry.npmjs.org/semver/-/semver-7.8.5.tgz', sha256: 'd85045d4300d7d57c891336b95df532e73f34c22ffcd222452b6d08b9d127d5d' },
    { name: '@img/colour', version: '1.1.0', url: 'https://registry.npmjs.org/@img/colour/-/colour-1.1.0.tgz', sha256: '6c2df3ac33d4b8647191ad8942a579e6004be00c25846677eab85f04702d85b1' },
    { name: 'detect-libc', version: '2.1.2', url: 'https://registry.npmjs.org/detect-libc/-/detect-libc-2.1.2.tgz', sha256: '270dec0fc06cff86481da8af2dd8f18dee6b602790b14ef0e1c2c18d7da39427' },
  ],
  platform: {
  'darwin-arm64': [
    { name: '@img/sharp-darwin-arm64', version: '0.35.5', url: 'https://registry.npmjs.org/@img/sharp-darwin-arm64/-/sharp-darwin-arm64-0.35.5.tgz', sha256: '52168af984c322e5548bebfb437a9976244824338ea5b8a5b1e0cdaaf06480cb' },
    { name: '@img/sharp-libvips-darwin-arm64', version: '1.3.4', url: 'https://registry.npmjs.org/@img/sharp-libvips-darwin-arm64/-/sharp-libvips-darwin-arm64-1.3.4.tgz', sha256: 'e8350e62344d027995ef46cdd97a5ea1c88bc54ab82ab8c3fcb0c076d839675f' },
  ],
  'linux-x64': [
    { name: '@img/sharp-linux-x64', version: '0.35.5', url: 'https://registry.npmjs.org/@img/sharp-linux-x64/-/sharp-linux-x64-0.35.5.tgz', sha256: '556787285d3244c07686a355de5b5a4c4d0019a12785bf24764e756a96ea3334' },
    { name: '@img/sharp-libvips-linux-x64', version: '1.3.4', url: 'https://registry.npmjs.org/@img/sharp-libvips-linux-x64/-/sharp-libvips-linux-x64-1.3.4.tgz', sha256: 'e371cb713fc8822c96a0d3fb60a3d092799d0aefab6d7f1fb3b72d8d75f1d109' },
  ],
  'linux-arm64': [
    { name: '@img/sharp-linux-arm64', version: '0.35.5', url: 'https://registry.npmjs.org/@img/sharp-linux-arm64/-/sharp-linux-arm64-0.35.5.tgz', sha256: '2ba164e9d4d2f56bfc2a1b8badff07f49d1c98c061dde23efbf97617d23be07d' },
    { name: '@img/sharp-libvips-linux-arm64', version: '1.3.4', url: 'https://registry.npmjs.org/@img/sharp-libvips-linux-arm64/-/sharp-libvips-linux-arm64-1.3.4.tgz', sha256: '495e6c63c797c6b080a9dbd827a8cc0790b77f8f7d5d82f1764dadfc5068a845' },
  ],
  },
}
