import { existsSync, readFileSync } from 'fs'
import { join } from 'path'

import type { AgentRuntimeAdapter } from '@bakin/core/adapters/runtime'

const EXEC_TOOLS_START = '<!-- bakin:exec-tools:start -->'
const EXEC_TOOLS_END = '<!-- bakin:exec-tools:end -->'

export interface BakinSkillStatus {
  installed: boolean
  upToDate: boolean
  expected: string
  current?: string
}

function buildExecToolsBlock(): string {
  const tools = getRegisteredExecTools()
  if (tools.length === 0) {
    return '\n<!-- No exec tools registered -->\n'
  }
  return `
## Live Exec Tools

> Auto-generated by Bakin from the live exec-tool registry.
> ${tools.length} tools are available. Use live discovery for complete schemas:

\`\`\`bash
mcporter list bakin-<agent> --schema
\`\`\`

The Bakin skill intentionally keeps this block compact so routine agent turns do not carry a large, stale tool catalog. Common task, workflow, team, asset, schedule, and health tools are listed above in the static quick reference.

### Discovery Examples

\`\`\`bash
mcporter list bakin-main --schema
mcporter call bakin-main.bakin_exec_health_status
\`\`\`
`
}

function getRegisteredExecTools(): unknown[] {
  try {
    const registry = require('../../scripts/lib/registry') as typeof import('../../scripts/lib/registry')
    return registry.getAllExecTools()
  } catch {
    return []
  }
}

export function renderBakinRuntimeSkill(projectRoot: string): string {
  const sourceSkill = join(projectRoot, 'skill', 'SKILL.md')
  if (!existsSync(sourceSkill)) {
    throw new Error('Bakin skill source not found at skill/SKILL.md')
  }

  const templateContent = readFileSync(sourceSkill, 'utf-8')
  const startIdx = templateContent.indexOf(EXEC_TOOLS_START)
  const endIdx = templateContent.indexOf(EXEC_TOOLS_END)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`skill/SKILL.md template is missing the ${EXEC_TOOLS_START} / ${EXEC_TOOLS_END} markers`)
  }

  const before = templateContent.slice(0, startIdx + EXEC_TOOLS_START.length)
  const after = templateContent.slice(endIdx)
  return `${before}${buildExecToolsBlock()}${after}`
}

export async function checkBakinRuntimeSkill(
  projectRoot: string,
  runtime: AgentRuntimeAdapter,
): Promise<BakinSkillStatus> {
  const expected = renderBakinRuntimeSkill(projectRoot)
  const installedSkill = await runtime.skills.get('bakin')
  const current = installedSkill?.instructions
  return {
    installed: Boolean(current),
    upToDate: current === expected,
    expected,
    ...(current ? { current } : {}),
  }
}

export async function syncBakinRuntimeSkill(
  projectRoot: string,
  runtime: AgentRuntimeAdapter,
): Promise<'installed' | 'updated' | 'noop'> {
  const status = await checkBakinRuntimeSkill(projectRoot, runtime)
  if (status.upToDate) return 'noop'

  await runtime.skills.write({
    name: 'bakin',
    instructions: status.expected,
    metadata: { source: 'bakin-onboarding' },
  })
  return status.installed ? 'updated' : 'installed'
}

export const _internals = {
  EXEC_TOOLS_START,
  EXEC_TOOLS_END,
  buildExecToolsBlock,
}
