/**
 * Bakin Doctor — health checks, OpenClaw sync, and auto-repair.
 * Runs on startup and on a configurable cadence to keep systems aligned.
 *
 * Auto-fix policy:
 *   SAFE (auto-fix):   Creating new files, installing/updating skill, making dirs
 *   UNSAFE (notify):   Agent roster mismatches, gateway down, task DB issues,
 *                      anything requiring human judgment
 *
 * Unsafe issues are reported to the main agent via OpenClaw so they show up in conversation.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'fs'
import { join } from 'path'
import { createLogger } from './logger'
import {
  extractBlock,
  getBlockState,
  injectBlock,
} from '../../packages/core/src/agent-packages/managed-blocks'
import { getSettings } from './settings'
import { getAgentIds } from '@bakin/core/openclaw-config'
import { getOpenClawPath } from '@bakin/core/openclaw-home'
import { appendAudit } from './audit'
import { isUsingBakinHome, getContentDir } from './content-dir'
import * as openclaw from './openclaw-client'
import * as mcporter from './mcporter'
import { isOnboarded } from './onboarding/state'
import { pluginAssetsComponent } from './onboarding/plugin-assets'
import { getMainAgentId, getMainAgentName } from './main-agent'
import { getAllExecTools } from '../../scripts/lib/registry'
import { getHookRegistry } from '../lib/plugin-registry'
import { listHealthChecks } from '../../plugins/health/lib/health-check-registry'

/**
 * Run every plugin-registered health check in parallel. Per-check try/catch
 * isolates failures — a single bad handler yields one synthetic error result
 * and never crashes the doctor sweep. Exported separately from runDiagnostics
 * so the isolation behavior can be tested without mocking every builtin
 * check's dependency tree.
 */
export async function runPluginHealthChecks(): Promise<DiagnosticResult[]> {
  const defs = listHealthChecks()
  const arrays = await Promise.all(
    defs.map(async (def) => {
      try {
        return await def.run()
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err)
        return [{
          check: def.id,
          status: 'error' as const,
          message: `Plugin health check threw: ${message}`,
          autoFixable: false,
        }]
      }
    }),
  )
  return arrays.flat()
}

const log = createLogger('doctor')

let doctorTimer: NodeJS.Timeout | null = null
let lastDiagnosticResults: DiagnosticResult[] | null = null
let lastDiagnosticTime: number = 0

// Track what we've already notified about to avoid spamming the main agent
const notifiedIssues = new Set<string>()

export interface DiagnosticResult {
  check: string
  status: 'ok' | 'warn' | 'error' | 'fixed'
  message: string
  autoFixable: boolean
}

function ok(check: string, message: string): DiagnosticResult {
  return { check, status: 'ok', message, autoFixable: false }
}

function warn(check: string, message: string, autoFixable = false): DiagnosticResult {
  return { check, status: 'warn', message, autoFixable }
}

function error(check: string, message: string): DiagnosticResult {
  return { check, status: 'error', message, autoFixable: false }
}

function fixed(check: string, message: string): DiagnosticResult {
  return { check, status: 'fixed', message, autoFixable: true }
}

// ---------------------------------------------------------------------------
// Individual checks — each returns diagnostics AND applies safe fixes
// ---------------------------------------------------------------------------

/**
 * Gateway: ping the OpenClaw gateway.
 * NOT auto-fixable — requires human intervention to start the gateway.
 */
async function checkGateway(): Promise<DiagnosticResult[]> {
  try {
    const alive = await openclaw.ping()
    if (alive) {
      return [ok('gateway', 'OpenClaw gateway is reachable')]
    }
    return [error('gateway', 'OpenClaw gateway is not responding')]
  } catch (err) {
    return [error('gateway', `Gateway check failed: ${err}`)]
  }
}

const EXEC_TOOLS_START = '<!-- bakin:exec-tools:start -->'
const EXEC_TOOLS_END = '<!-- bakin:exec-tools:end -->'

/**
 * Build the exec-tools block body from the current tool registry.
 * Returns the inner content that gets placed between the start/end markers
 * (without the markers themselves). Stable across runs when the registry
 * hasn't changed, so the sync check can compare string equality.
 */
function buildExecToolsBlock(): string {
  const tools = getAllExecTools()
  if (tools.length === 0) {
    return '\n<!-- No exec tools registered -->\n'
  }
  const toolLines = tools
    .map(t => `| \`${t.name}\` | ${t.description} |`)
    .join('\n')
  return `
## Execution Tools

> Auto-generated by \`bakin doctor\` from the exec-tool registry.
> Source of truth is the template at \`skill/SKILL.md\` plus the runtime registry.
> The repo template's managed block is intentionally empty — this file is rendered on sync.

Use these tools to accomplish actual work — saving files, posting content, generating images, scheduling jobs. Called the same way as MCP tools via mcporter.

| Tool | Purpose |
|------|---------|
${toolLines}

### Quick Reference

\`\`\`bash
# Save a file as a managed asset (handles naming + sidecar automatically)
mcporter call bakin-<agent>.bakin_exec_save_asset taskId=<id> type=<images|text|video|audio|plans|data|other> filePath="<path>" description="<desc>"
# Post to Discord (with optional image/video attachment)
mcporter call bakin-<agent>.bakin_exec_post_discord channel="<name>" content="<msg>" taskId=<id>
# Generate image via Nano Banana
mcporter call bakin-<agent>.bakin_exec_gen_image taskId=<id> prompt="<text>" preset=social-portrait model=flash
# Check workflow gate statuses
mcporter call bakin-<agent>.bakin_exec_check_gates taskId=<id>
# Create a recurring scheduled job (NEVER use openclaw cron directly)
mcporter call bakin-<agent>.bakin_exec_schedule_create name="daily-recipe" schedule="every day at 11am" agentId="chef" taskPrompt="Post a short recipe"
# List all scheduled jobs
mcporter call bakin-<agent>.bakin_exec_schedule_list
\`\`\`
`
}

/**
 * Render the synced skill file: take the repo template, inject the current
 * exec-tools block between its markers, and return the full file contents.
 * Throws if the template is missing the markers — the template is checked
 * into the repo so missing markers is a bug, not an auto-fix case.
 */
function renderSyncedSkill(templateContent: string): string {
  const startIdx = templateContent.indexOf(EXEC_TOOLS_START)
  const endIdx = templateContent.indexOf(EXEC_TOOLS_END)
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`skill/SKILL.md template is missing the ${EXEC_TOOLS_START} / ${EXEC_TOOLS_END} markers`)
  }
  const before = templateContent.slice(0, startIdx + EXEC_TOOLS_START.length)
  const after = templateContent.slice(endIdx)
  return `${before}${buildExecToolsBlock()}${after}`
}

/**
 * Skill: render the Bakin skill template + install/update it in the OpenClaw
 * workspace. The repo's `skill/SKILL.md` is the source of truth for static
 * content only — the exec-tools block between the markers is generated at
 * sync time from the live registry and written ONLY to the OpenClaw copy.
 * Auto-fixable — safe because it creates/overwrites only our own skill file.
 */
function checkAndSyncSkill(projectRoot: string, autoFix: boolean): DiagnosticResult[] {
  const sourceSkill = join(projectRoot, 'skill', 'SKILL.md')
  if (!existsSync(sourceSkill)) {
    return [error('skill', 'Bakin skill source not found at skill/SKILL.md')]
  }

  const templateContent = readFileSync(sourceSkill, 'utf-8')
  let renderedContent: string
  try {
    renderedContent = renderSyncedSkill(templateContent)
  } catch (err) {
    return [error('skill', `Failed to render skill template: ${(err as Error).message}`)]
  }

  const workspaceSkillDir = getOpenClawPath('workspace', 'skills', 'bakin')
  const targetSkill = join(workspaceSkillDir, 'SKILL.md')

  if (!existsSync(targetSkill)) {
    if (!autoFix) {
      return [warn('skill', 'Bakin skill not installed in OpenClaw', true)]
    }
    try {
      mkdirSync(workspaceSkillDir, { recursive: true })
      writeFileSync(targetSkill, renderedContent, 'utf-8')
      writeFileSync(join(workspaceSkillDir, '_meta.json'), JSON.stringify({
        slug: 'bakin',
        version: '1.0.0',
        installedAt: Date.now(),
        source: 'bakin-doctor',
      }, null, 2), 'utf-8')
      return [fixed('skill', 'Bakin skill installed in OpenClaw workspace')]
    } catch (err) {
      return [error('skill', `Failed to install skill: ${err}`)]
    }
  }

  const currentContent = readFileSync(targetSkill, 'utf-8')
  if (currentContent === renderedContent) {
    return [ok('skill', 'Bakin skill is up to date')]
  }

  // Safety guard: if the currently-installed copy has more exec tools than
  // the render we just built, it means the caller's tool registry is
  // incomplete — most likely because this is a standalone CLI run that
  // didn't activate plugins. Refuse to overwrite rather than silently
  // truncate the installed file. The server-boot path, which activates all
  // plugins, will render the full set and sync on its next cycle.
  const countTools = (text: string) => (text.match(/\| `bakin_exec_/g) || []).length
  const currentCount = countTools(currentContent)
  const renderedCount = countTools(renderedContent)
  if (renderedCount < currentCount) {
    return [warn(
      'skill',
      `Refusing to sync — rendered tool count (${renderedCount}) is less than installed (${currentCount}). ` +
      `Plugins likely not activated in this process. Restart the server to let the boot-time doctor render the full set.`,
      false,
    )]
  }

  if (!autoFix) {
    return [warn('skill', 'Bakin skill is outdated in OpenClaw', true)]
  }

  try {
    writeFileSync(targetSkill, renderedContent, 'utf-8')
    const metaPath = join(workspaceSkillDir, '_meta.json')
    let meta: Record<string, unknown> = {}
    if (existsSync(metaPath)) {
      try { meta = JSON.parse(readFileSync(metaPath, 'utf-8')) } catch { /* fresh */ }
    }
    const currentVersion = String(meta.version || '1.0.0')
    const parts = currentVersion.split('.').map(Number)
    parts[2] = (parts[2] || 0) + 1
    meta.version = parts.join('.')
    meta.updatedAt = Date.now()
    meta.source = 'bakin-doctor'
    writeFileSync(metaPath, JSON.stringify(meta, null, 2), 'utf-8')
    return [fixed('skill', `Bakin skill updated to v${meta.version}`)]
  } catch (err) {
    return [error('skill', `Failed to update skill: ${err}`)]
  }
}

/**
 * Antfly: verify binary installed and connection when enabled.
 * Binary check is informational when disabled, error when enabled and missing.
 */
async function checkAntfly(): Promise<DiagnosticResult[]> {
  const settings = getSettings()
  const { installed } = await import('./antfly-server')

  if (!settings.antfly.enabled) {
    if (!installed()) {
      return [warn('antfly', 'Antfly disabled and binary not installed — install with: brew install --cask antflydb/antfly/antfly')]
    }
    return [ok('antfly', 'Antfly disabled — binary installed, enable with: bakin settings set antfly.enabled true')]
  }

  if (!installed()) {
    return [error('antfly', 'Antfly enabled but binary not found — install with: brew install --cask antflydb/antfly/antfly')]
  }

  const urls = Array.from(new Set([
    settings.antfly.url.replace(/\/api\/v1\/?$/, ''),
    settings.antfly.url.replace('localhost', '127.0.0.1').replace(/\/api\/v1\/?$/, ''),
  ]))

  let lastErr: unknown
  for (const base of urls) {
    try {
      const res = await fetch(`${base}/api/v1/status`, { signal: AbortSignal.timeout(3000) })
      if (res.ok) {
        const status = await res.json()
        return [ok('antfly', `Antfly connected (health: ${status?.health})`)]
      }
      lastErr = new Error(`status ${res.status}`)
    } catch (err) {
      lastErr = err
    }
  }

  return [error('antfly', `Antfly connection failed: ${lastErr}`)]
}

/**
 * Search tables: verify registered content types have tables with data.
 * Runs only when Antfly is enabled and connected.
 */
async function checkSearchTables(): Promise<DiagnosticResult[]> {
  const settings = getSettings()
  if (!settings.antfly.enabled) return []

  try {
    const antfly = await import('./antfly')
    await antfly.initialize()

    // If Antfly is configured but unavailable, the antfly diagnostic is the
    // root cause. Skip downstream search-table noise until the connection is
    // healthy again.
    if (!antfly.available()) return []

    const { getSearchHealth } = await import('./search-registry')
    const health = await getSearchHealth()

    if (!health.enabled) return []

    const results: DiagnosticResult[] = []

    if (health.tables.length === 0) {
      results.push(warn('search-tables', 'Antfly enabled but no content types registered — plugins may not have activated'))
      return results
    }

    let emptyTables = 0
    let failedTables = 0

    for (const t of health.tables) {
      if (!t.stats) {
        failedTables++
        results.push(warn('search-tables', `Table "${t.table}" (${t.pluginId}) — stats unavailable, but table is registered${t.healthy ? ' and indexes look healthy' : ''}`))
        continue
      }

      const rawNumDocs = Number((t.stats as Record<string, unknown>).num_docs)
      if (Number.isFinite(rawNumDocs)) {
        if (rawNumDocs === 0) {
          if (t.pluginId === 'schedule') {
            results.push(ok('search-tables', `Table "${t.table}" (${t.pluginId}) has 0 persisted documents; schedule jobs are indexed at runtime`))
          } else {
            emptyTables++
            results.push(ok('search-tables', `Table "${t.table}" (${t.pluginId}) has 0 documents — reindex via POST /api/reindex?table=${t.table}`))
          }
        }
        continue
      }

      const storage = (t.stats as Record<string, unknown>).storage_status as Record<string, unknown> | undefined
      if (storage?.empty === true) {
        emptyTables++
        results.push(ok('search-tables', `Table "${t.table}" (${t.pluginId}) appears empty — reindex via POST /api/reindex?table=${t.table}`))
      }
    }

    if (results.length === 0) {
      const totals = health.tables
        .map(t => Number((t.stats as Record<string, unknown>)?.num_docs))
        .filter(n => Number.isFinite(n))

      if (totals.length > 0) {
        const total = totals.reduce((sum, n) => sum + n, 0)
        results.push(ok('search-tables', `${health.tables.length} tables, ${total} total documents indexed`))
      } else if (failedTables > 0) {
        results.push(warn('search-tables', `${health.tables.length} tables registered; ${failedTables} table stats unavailable, but registry metadata is readable`))
      } else {
        results.push(ok('search-tables', `${health.tables.length} tables registered; table metadata readable (document counts unavailable from current Antfly API)`))
      }
    }

    return results
  } catch (err) {
    return [error('search-tables', `Failed to check search tables: ${err}`)]
  }
}

/**
 * Content directory: verify content lives in ~/.bakin/ not ./content/.
 * NOT auto-fixable — migration requires user judgment (moving live data).
 */
function checkContentDir(): DiagnosticResult[] {
  const contentDir = getContentDir()
  if (isUsingBakinHome()) {
    return [ok('content-dir', `Content directory: ${contentDir}`)]
  }
  return [warn('content-dir',
    `Content lives at ${contentDir} instead of ~/.bakin/ — run: bakin init && move content/* to ~/.bakin/`
  )]
}

/**
 * Orchestrator rules: verify AGENTS.md has the Bakin rules block and it's current.
 * Auto-fixable — safe to write/update our own block in AGENTS.md.
 */
export const AGENT_RULES_BLOCK_START = '<!-- bakin:orchestrator-rules:start -->'
export const AGENT_RULES_BLOCK_END = '<!-- bakin:orchestrator-rules:end -->'

const ORCHESTRATOR_RULES_CONTENT = `## Bakin Orchestrator Rules

> Auto-managed by \`bakin agent-rules --apply\`. Do not edit this block manually.

These rules govern AGENT_NAME_PLACEHOLDER as orchestrator of the Bakin multi-agent system.

1. **Every task gets logged before work begins.** Call \`bakin_exec_tasks_create\` via MCP before spawning any subagent or producing any deliverable. No exceptions.

    A task is anything that spawns a subagent, produces a deliverable (image, code, document, post), requires research, or gets handed off. NOT a task: quick questions, reactions, casual banter, acknowledgements. If it involves a verb (generate, build, research, write, fix, create), it's a task — log it first, then do it.

2. **Never do subagent work inline.** AGENT_NAME_PLACEHOLDER delegates — AGENT_NAME_PLACEHOLDER does not generate images, write long-form copy, or produce video. That's what the team is for.

3. **High-level tasks only on the board.** Don't break tasks into subtasks yourself. Create one task, assign it, let the subagent decompose it.

4. **Subagents own their handoffs.** If Chef needs Pixel, Chef creates that task — not AGENT_NAME_PLACEHOLDER. Let the pipeline flow naturally.

5. **Approval gates are non-negotiable.** Before publishing, sending, or any external action: pause and confirm with Mark unless pre-approved.

6. **Monitor the pipeline, don't micromanage.** Check heartbeats, watch for blocked tasks, intervene when stuck — but don't shadow-execute tasks that are in flight.

7. **One task per agent per piece of content.** Don't assign the same content to multiple agents in parallel. Let the assigned agent drive.

8. **AGENTS.md is your rulebook, not the subagents'.** The Bakin skill (SKILL.md) governs subagents. AGENTS.md governs you.

9. **Workflow tasks are hands-off.** If a task has a \`workflowId\`, the workflow engine manages step progression. Do not manually move workflow tasks between columns, do not produce step output yourself, and do not interfere with gates outside the Bakin UI.

10. **Every task requires a workflow decision. Workflows are the default — skipping is the exception.** When calling \`bakin_exec_tasks_create\`, you MUST either specify a \`workflowId\` or explain why none applies via \`skipWorkflowReason\`:
    - With workflow: \`{ title, assignee, workflowId: "<id>" }\`
    - Without workflow: \`{ title, assignee, skipWorkflowReason: "<reason>" }\`

    **Preflight sequence — follow these steps in order, every time:**
    1. Call \`bakin_exec_workflows_list\` and read the catalog.
    2. Check if any workflow matches the request (by title keywords, agent, or intent).
    3. **If a matching workflow exists, DO NOT create the task yet.** Reply to the requester with the workflow's tradeoffs and ask them to choose. Example: *"There's an \`image-generation\` workflow with a prompt-approval gate — want the full workflow, or should I do a quick one-off?"* **Silence is not permission to skip.** Wait for an explicit choice.
    4. Only after the requester's decision, call \`bakin_exec_tasks_create\` — either with \`workflowId\` set to what they picked, or with \`skipWorkflowReason\` citing the confirmation (e.g., \`"Mark approved skipping image-generation in chat — one-off horse image, no approval gate needed"\`).

    **Chat requests that sound simple are still workflow candidates if a matching workflow exists.** "Have Pixel make an image of a horse" is NOT a reason to bypass \`image-generation\`. The user's phrasing doesn't change the rule — the catalog does.

    **Your judgment is not enough to skip.** "This feels heavier than needed," "this is a one-off," and "this is quick" are NOT valid reasons on their own. The only valid reasons to skip without asking first: (a) no workflow in the catalog matches the request, or (b) the requester has already said in this conversation that they want a one-off.

    The catalog snapshot below is a hint, not the source of truth. **Always trust the live output of \`bakin_exec_workflows_list\` over any text in this file.** The snapshot is frozen at the last doctor run and may be stale, empty, or out of date; the tool is authoritative.

    Workflow catalog snapshot (last rendered by \`bakin agent-rules --apply\`):
WORKFLOW_CATALOG_PLACEHOLDER

The skip reason is logged to the audit trail for debugging. Always verify against \`bakin_exec_workflows_list\` before deciding a workflow doesn't exist.

11. **Gate approvals go through the UI.** When a workflow gate is reached, a notification is sent and the task card shows "Awaiting Approval" in the Bakin UI. Tell Mark a gate is waiting — do NOT approve or reject gates yourself. Mark handles gates in the task drawer.

12. **MCP tools only. No REST. No CLI. Ever.** All orchestration happens through the \`bakin_exec_*\` MCP tools. OpenClaw has no native MCP client, so you reach them by shelling out to **mcporter** — a CLI shim that relays your call to Bakin's MCP server. Your server is \`bakin-AGENT_ID_PLACEHOLDER\`.

    **Invocation pattern (positional args):**
    \`\`\`
    mcporter call bakin-AGENT_ID_PLACEHOLDER.<tool_name> key=value key=value
    \`\`\`

    **Invocation pattern (JSON args, for nested/complex inputs):**
    \`\`\`
    mcporter call bakin-AGENT_ID_PLACEHOLDER.<tool_name> --args '{"key":"value","nested":{"k":"v"}}'
    \`\`\`

    **Discovery:** \`mcporter list bakin-AGENT_ID_PLACEHOLDER --schema\` prints every available tool with its input schema. Run it when you're not sure what's available. Do NOT guess tool names.

    The REST API at \`/api/plugins/*\` and the \`bakin\` CLI both exist for humans, the web UI, and scripting — NOT for you. If a capability appears to be missing from MCP, STOP and tell Mark so we can add the tool. Do not curl, do not fetch, do not shell out to \`bakin tasks ...\`, do not write scripts that hit \`/api/...\`. Every REST call from an agent surfaces on the Health dashboard as a bad-habit signal.

    **Core orchestration tools** (non-exhaustive — run discovery for the full list):
    - Tasks: \`bakin_exec_tasks_create\`, \`bakin_exec_tasks_get\`, \`bakin_exec_tasks_move\`, \`bakin_exec_tasks_log_progress\`, \`bakin_exec_tasks_complete\`, \`bakin_exec_tasks_block\`
    - Workflows: \`bakin_exec_workflows_list\`, \`bakin_exec_workflows_get_definition\`, \`bakin_exec_workflows_start\`, \`bakin_exec_workflows_get_instance\`, \`bakin_exec_workflows_get_step\`, \`bakin_exec_workflows_complete_step\`
    - Team: \`bakin_exec_team_list\`, \`bakin_exec_team_status\`, \`bakin_exec_team_message\`
    - Health: \`bakin_exec_health_status\`, \`bakin_exec_health_doctor\`

    **Example — create a task for Pixel:**
    \`\`\`
    mcporter call bakin-AGENT_ID_PLACEHOLDER.bakin_exec_tasks_create --args '{"title":"Create a stylized image of a horse","assignee":"pixel","skipWorkflowReason":"one-off request, no workflow matches"}'
    \`\`\`

13. **Never impersonate other agents.** You are AGENT_NAME_PLACEHOLDER. You do not speak as Chef, Pixel, Flint, Nori, or any other team member. You do not write their task updates, fabricate their progress logs, or mark their tasks done on their behalf. If an agent is silent or stuck, create a follow-up task or tell Mark — do not ventriloquize.

14. **The channel doesn't change the rules.** These rules apply whether Mark is talking to you in the Bakin UI, a group chat, the terminal, or any other surface. There is no "informal mode" where CLI, REST, or inline subagent work becomes acceptable.`

/** Build the workflow catalog from available definitions for embedding in rules */
async function buildWorkflowCatalog(): Promise<string> {
  try {
    const hooks = getHookRegistry()
    const defs = await hooks.invoke<Array<{ definition: Record<string, unknown>; name: string }>>('workflows.listDefinitions', {}) ?? []
    if (defs.length === 0) return '   (no workflows defined yet)'
    return defs.map(d => {
      const steps = (d.definition.steps || []) as Array<Record<string, unknown>>
      const agents = [...new Set(steps.filter((s) => typeof s.agent === 'string').map((s) => s.agent as string))]
      return `   - \`${d.name}\`: ${d.definition.description || d.definition.name}${agents.length ? ` (agents: ${agents.join(', ')})` : ''}`
    }).join('\n')
  } catch {
    return '   (query GET /api/plugins/workflows/definitions at runtime)'
  }
}

/** Resolve the orchestrator rules template with the current workflow catalog and main agent id */
export async function resolveOrchestratorRules(): Promise<string> {
  const agentId = getMainAgentId()
  const agentName = getMainAgentName()
  return ORCHESTRATOR_RULES_CONTENT
    .replace('WORKFLOW_CATALOG_PLACEHOLDER', await buildWorkflowCatalog())
    .replaceAll('AGENT_ID_PLACEHOLDER', agentId)
    .replaceAll('AGENT_NAME_PLACEHOLDER', agentName)
}

async function checkOrchestratorRules(autoFix: boolean): Promise<DiagnosticResult[]> {
  const agentsPath = getOpenClawPath('workspace', 'AGENTS.md')

  if (!existsSync(agentsPath)) {
    return [warn('orchestrator-rules', 'AGENTS.md not found — cannot verify orchestrator rules')]
  }

  const resolvedContent = await resolveOrchestratorRules()
  const current = readFileSync(agentsPath, 'utf-8')
  const startIdx = current.indexOf(AGENT_RULES_BLOCK_START)
  const endIdx = current.indexOf(AGENT_RULES_BLOCK_END)
  const hasBlock = startIdx !== -1

  if (!hasBlock) {
    if (!autoFix) {
      return [warn('orchestrator-rules', 'Orchestrator rules block missing from AGENTS.md — run: bakin agent-rules --apply', true)]
    }
    const block = `${AGENT_RULES_BLOCK_START}\n${resolvedContent}\n${AGENT_RULES_BLOCK_END}\n`
    writeFileSync(agentsPath, current.trimEnd() + '\n\n' + block, 'utf-8')
    return [fixed('orchestrator-rules', 'Added orchestrator rules block to AGENTS.md')]
  }

  if (endIdx === -1) {
    return [error('orchestrator-rules', 'Orchestrator rules block start marker found but no end marker — AGENTS.md may be corrupt')]
  }

  const blockContent = current.slice(startIdx + AGENT_RULES_BLOCK_START.length, endIdx).trim()
  const expected = resolvedContent.trim()

  if (blockContent === expected) {
    return [ok('orchestrator-rules', 'Orchestrator rules block present and up to date')]
  }

  if (!autoFix) {
    return [warn('orchestrator-rules', 'Orchestrator rules block is outdated — run: bakin agent-rules --apply', true)]
  }

  const block = `${AGENT_RULES_BLOCK_START}\n${resolvedContent}\n${AGENT_RULES_BLOCK_END}`
  const updated = current.slice(0, startIdx) + block + current.slice(endIdx + AGENT_RULES_BLOCK_END.length)
  writeFileSync(agentsPath, updated, 'utf-8')
  return [fixed('orchestrator-rules', 'Updated orchestrator rules block in AGENTS.md')]
}

/**
 * mcporter: verify installation and per-agent config entries.
 * Auto-fixable — safe because it only installs a CLI tool and writes config.
 */
function checkMcporter(port: number, autoFix: boolean): DiagnosticResult[] {
  const results: DiagnosticResult[] = []

  if (!mcporter.isMcporterInstalled()) {
    if (!autoFix) {
      return [warn('mcporter', 'mcporter not installed — run: bakin setup mcporter', true)]
    }
    if (!mcporter.installMcporter()) {
      return [error('mcporter', 'Failed to install mcporter — run: npm i -g mcporter')]
    }
    results.push(fixed('mcporter', 'Installed mcporter globally'))
  }

  const status = mcporter.verifyConfig(port)

  const missing = status.agentEntries.filter(e => !e.correct)
  if (missing.length > 0) {
    if (!autoFix) {
      return [
        ...results,
        warn('mcporter', `${missing.length} agent(s) missing or outdated in mcporter config — run: bakin setup mcporter`, true),
      ]
    }
    const changes = mcporter.syncConfig(port)
    results.push(fixed('mcporter', `Config updated: ${changes.join(', ')}`))
  } else {
    results.push(ok('mcporter', `All ${status.agentEntries.length} agent entries configured`))
  }

  if (status.staleEntries.length > 0 && autoFix) {
    mcporter.syncConfig(port) // syncConfig already removes stale
  }

  return results
}

/**
 * Service: verify the macOS LaunchAgent is installed with correct paths.
 * NOT auto-fixable — stale paths require human judgment.
 */
function checkService(projectRoot: string): DiagnosticResult[] {
  const settings = getSettings()
  if (!settings.service.enabled) {
    return [ok('service', 'Skipped — service management disabled in settings')]
  }

  if (process.platform !== 'darwin') {
    return [ok('service', 'Skipped — macOS only')]
  }

  const results: DiagnosticResult[] = []
  const homedir = process.env.HOME || '~'
  const plistPath = join(homedir, 'Library', 'LaunchAgents', 'com.openclaw.mc.plist')

  if (!existsSync(plistPath)) {
    results.push(warn('service', 'LaunchAgent plist not found — run: bakin setup service'))
    return results
  }

  try {
    const plistContent = readFileSync(plistPath, 'utf-8')

    // Check WorkingDirectory matches current project
    const wdMatch = plistContent.match(/<key>WorkingDirectory<\/key>\s*<string>([^<]+)<\/string>/)
    if (wdMatch && wdMatch[1] !== projectRoot) {
      results.push(error('service',
        `LaunchAgent WorkingDirectory is "${wdMatch[1]}" but project is at "${projectRoot}" — run: bakin setup service`
      ))
    }

    // Check server.ts path matches
    const serverMatch = plistContent.match(/<string>([^<]*server\.ts)<\/string>/)
    if (serverMatch && serverMatch[1] !== join(projectRoot, 'server.ts')) {
      results.push(error('service',
        `LaunchAgent references stale server.ts path — run: bakin setup service`
      ))
    }
  } catch (err) {
    results.push(error('service', `Failed to read plist: ${err}`))
    return results
  }

  // Check service is loaded
  try {
    const { execSync } = require('child_process')
    execSync('launchctl list com.openclaw.mc', { encoding: 'utf-8', stdio: 'pipe' })
  } catch {
    results.push(warn('service', 'LaunchAgent plist exists but service is not loaded — run: bakin setup service'))
  }

  if (results.length === 0) {
    results.push(ok('service', 'LaunchAgent installed and loaded with correct paths'))
  }

  return results
}


// ---------------------------------------------------------------------------
// Notification — escalate unfixable issues to the main agent
// ---------------------------------------------------------------------------

async function notifyUnfixableIssues(results: DiagnosticResult[]): Promise<void> {
  const issues = results.filter(r =>
    (r.status === 'warn' || r.status === 'error') && !r.autoFixable
  )

  if (issues.length === 0) return

  // Build a dedup key from the issues so we don't spam
  const issueKey = issues.map(i => `${i.check}:${i.status}`).sort().join('|')
  if (notifiedIssues.has(issueKey)) return
  notifiedIssues.add(issueKey)

  const lines = issues.map(i => {
    const icon = i.status === 'error' ? 'ERROR' : 'WARN'
    return `[${icon}] ${i.check}: ${i.message}`
  })

  const message = `Bakin Doctor found ${issues.length} issue(s) that need your attention:\n\n${lines.join('\n')}\n\nRun \`bakin doctor\` for full details.`

  try {
    await openclaw.sendMessage(getMainAgentId(), message)
    log.info('Notified main agent of unfixable issues', { count: issues.length })
  } catch (err) {
    // Gateway might be the issue — can't notify about that
    log.warn('Could not notify main agent of doctor issues (gateway may be down)', err)
  }
}

// ---------------------------------------------------------------------------
// Generic managed block helper
// ---------------------------------------------------------------------------

interface ManagedBlockDef {
  blockId: string
  contentFn: (agentId: string) => string
  agentFilter?: (agentId: string) => boolean // defaults to all non-main-agent
}

/**
 * Check/inject/update a managed block in each agent's AGENTS.md.
 *
 * The marker primitives — `getBlockState`, `extractBlock`, `injectBlock` —
 * live in `packages/core/src/agent-packages/managed-blocks.ts` and are
 * shared with the agent-package installer/projector. This function is the
 * doctor-shaped wrapper around them: it translates marker state into
 * DiagnosticResult shapes and applies the autoFix policy.
 *
 * All managed blocks follow the same marker pattern:
 *   <!-- bakin:{blockId}:start -->
 *   {content}
 *   <!-- bakin:{blockId}:end -->
 */
function checkManagedBlock(def: ManagedBlockDef, autoFix: boolean): DiagnosticResult[] {
  const results: DiagnosticResult[] = []
  const openclawBase = getOpenClawPath()
  const checkName = `agent-${def.blockId}`

  const mainId = getMainAgentId()
  for (const agentId of getAgentIds()) {
    if (agentId === mainId) continue
    if (def.agentFilter && !def.agentFilter(agentId)) continue

    const agentsPath = join(openclawBase, 'workspaces', agentId, 'AGENTS.md')

    if (!existsSync(agentsPath)) {
      results.push(warn(checkName, `AGENTS.md not found for ${agentId} — cannot verify ${def.blockId}`))
      continue
    }

    const current = readFileSync(agentsPath, 'utf-8')
    const expectedBody = def.contentFn(agentId).trim()
    const state = getBlockState(current, def.blockId)

    if (state === 'orphan-start' || state === 'orphan-end') {
      // Malformed marker pair — refuse to silently rewrite. The user's
      // intent isn't clear (mid-edit? merge conflict remnant?), and
      // overwriting could destroy unsynced work.
      results.push(error(
        checkName,
        `${def.blockId} block has malformed markers (${state}) in ${agentId}/AGENTS.md`,
      ))
      continue
    }

    if (state === 'absent') {
      if (!autoFix) {
        results.push(warn(checkName, `${def.blockId} block missing from ${agentId}/AGENTS.md`, true))
        continue
      }
      writeFileSync(agentsPath, injectBlock(current, def.blockId, expectedBody), 'utf-8')
      results.push(fixed(checkName, `Added ${def.blockId} block to ${agentId}/AGENTS.md`))
      continue
    }

    // state === 'present'
    const currentBody = extractBlock(current, def.blockId) ?? ''
    if (currentBody === expectedBody) {
      results.push(ok(checkName, `${def.blockId} in ${agentId}/AGENTS.md is up to date`))
    } else if (autoFix) {
      writeFileSync(agentsPath, injectBlock(current, def.blockId, expectedBody), 'utf-8')
      results.push(fixed(checkName, `Updated ${def.blockId} block in ${agentId}/AGENTS.md`))
    } else {
      results.push(warn(checkName, `${def.blockId} block is outdated in ${agentId}/AGENTS.md`, true))
    }
  }

  return results
}

// ---------------------------------------------------------------------------
// Managed block definitions
// ---------------------------------------------------------------------------

const MANAGED_BLOCKS: ManagedBlockDef[] = [
  {
    blockId: 'mission-control',
    contentFn: (agentId: string) => `## Bakin Mission Control

> Auto-managed by \`bakin doctor\`. Do not edit this block manually.

All Bakin interactions use **mcporter**. Your MCP server is \`bakin-${agentId}\`.

### Session Start
1. Check your tasks: \`mcporter call bakin-${agentId}.bakin_exec_tasks_get taskId=<id>\`
2. Load the Bakin skill for full conventions and tool reference

### Path Discovery
All content paths are resolved via mcporter — never hardcode paths:
\`\`\`bash
mcporter call bakin-${agentId}.bakin_exec_get_paths
\`\`\`

### Task Changes
- Use \`bakin_exec_tasks_complete\` when done, \`bakin_exec_tasks_block\` when stuck
- Use Bakin tools via mcporter for all task operations

### Heartbeat (every 10 minutes)
- Write your heartbeat JSON to the heartbeats path (discover via \`bakin_exec_get_paths\`)
- Check for new tasks via mcporter`,
  },

  {
    blockId: 'hard-rules',
    contentFn: (agentId: string) => `## Bakin Hard Rules

> Auto-managed by \`bakin doctor\`. Do not edit this block manually.

- **NEVER use \`openclaw agent\` to spawn or message other agents directly.** Always create a Bakin task via \`mcporter call bakin-${agentId}.bakin_exec_tasks_create title="<task>" assignee="<agent>"\` instead. Direct spawning bypasses the pipeline.
- **NEVER modify task state directly.** Use Bakin tools via mcporter only.
- **NEVER post to Discord without explicit instruction.** Content goes through Mark's review first.
- **NEVER hardcode file paths.** Always discover paths via \`mcporter call bakin-${agentId}.bakin_exec_get_paths\`. Hardcoded paths break when the content directory moves.
- **NEVER run scripts/bin/*.ts directly.** Those are debug wrappers that bypass Bakin tracking — no MCP call, no Health metrics, no audit log. Always use the MCP tool via \`mcporter call bakin-${agentId}.bakin_exec_<tool> ...\` instead.
- **NEVER use \`openclaw cron\` directly for recurring tasks.** Use \`mcporter call bakin-${agentId}.bakin_exec_schedule_create name="..." schedule="every day at 9am" agentId="..." taskPrompt="..."\` instead. Direct cron jobs bypass Bakin — no agent context, no task creation, no audit trail.`,
  },

  {
    blockId: 'dependency-pattern',
    contentFn: (agentId: string) => `## Bakin Dependency Pattern

> Auto-managed by \`bakin doctor\`. Do not edit this block manually.

If your task requires output from another agent, create their task first, note its task ID, then register a dependency:
\`\`\`bash
mcporter call bakin-${agentId}.bakin_exec_tasks_set_dependency taskId=<your-task-id> dependsOn=<their-task-id>
\`\`\`
Then exit — you will be automatically re-dispatched when their task completes.`,
  },

  {
    blockId: 'media-delegation',
    contentFn: (agentId: string) => {
      const canImage = agentId === 'pixel'
      const canVideo = agentId === 'rolo'
      const createsSubtasks = !canImage // everyone except pixel creates pixel subtasks

      let content = `## Bakin Media Delegation Rules

> Auto-managed by \`bakin doctor\`. Do not edit this block manually.\n`

      if (!canImage) {
        content += `\n**IMAGES:** You cannot generate images. Ever. Not with nano-banana-pro, not with any other tool. All image generation goes through Pixel. Create a Pixel task via \`mcporter call bakin-${agentId}.bakin_exec_tasks_create\` and wait.\n`
      }

      if (!canVideo) {
        content += `\n**VIDEO:** You cannot generate video. Ever. Not with Runway, not with any other tool. All video generation goes through Rolo. Create a Rolo task via \`mcporter call bakin-${agentId}.bakin_exec_tasks_create\` and wait.\n`
      }

      if (!canImage && !canVideo) {
        content += `\nIf you find yourself about to run an image or video generation tool — stop. Create a subtask for the right agent instead.\n`
      }

      if (createsSubtasks) {
        content += `\n### When Creating Pixel or Rolo Tasks\n`
        content += `\n- **NEVER include posting instructions in a Pixel or Rolo brief.** They generate assets only — they do not post.`
        content += `\n- Task descriptions for Pixel/Rolo should end with asset delivery: "Save to the assets directory (discover path via \`bakin_exec_get_paths\`) and report the file path."`
        content += `\n- YOU are responsible for posting the finished content. Not Pixel. Not Rolo.`
      }

      return content
    },
  },

  {
    blockId: 'workflow-rules',
    contentFn: (agentId: string) => `## Bakin Workflow Rules

> Auto-managed by \`bakin doctor\`. Do not edit this block manually.

When Bakin dispatches a workflow step to you, the dispatch message contains everything you need: step instructions, output schema, and the mcporter command to submit.

1. **The dispatch message is your single source of truth.** Follow it exactly for workflow steps.

2. **Submit output ONLY via mcporter:** \`mcporter call bakin-${agentId}.bakin_exec_submit_step taskId=<id> stepId=<step> --args '<json>'\`. Conversational output does NOT complete the step.

3. **Do NOT move the task, create subtasks, or message ${getMainAgentName()}** for workflow tasks — the workflow engine handles all coordination.

4. **Address rejection feedback specifically.** If re-dispatched with "REVISION REQUIRED", read the feedback and produce genuinely revised output. The server rejects near-duplicate resubmissions.

5. **After submitting, STOP.** Do not generate additional outputs, start work on future steps, or send completion messages.

6. **Respect tool restrictions.** If the dispatch message lists "TOOL RESTRICTIONS", do NOT use those tools. Block the task if you need them.`,
  },

  {
    blockId: 'scheduling-rules',
    contentFn: (agentId: string) => `## Bakin Scheduling Rules

> Auto-managed by \`bakin doctor\`. Do not edit this block manually.

**NEVER use \`openclaw cron\` directly for recurring tasks.** Always use Bakin's schedule tools via mcporter. Direct cron jobs bypass Bakin tracking — no agent avatar, no prompt context, no task creation, no run history.

### Creating Scheduled Jobs
\`\`\`bash
mcporter call bakin-${agentId}.bakin_exec_schedule_create name="daily-recipe" schedule="every day at 11am" agentId="chef" taskPrompt="Post a short recipe into #general"
\`\`\`
- \`schedule\` accepts natural language ("every weekday at 9am", "every Monday and Thursday at 10am") or raw cron ("0 9 * * 1-5")
- Each scheduled run creates a Bakin task on the board, assigned to the specified agent
- Timezone is auto-detected (system IANA tz)

### Other Schedule Tools
- \`bakin_exec_schedule_list\` — View all jobs (filter by agent or bakin-only)
- \`bakin_exec_schedule_update\` — Change schedule, agent, prompt, etc.
- \`bakin_exec_schedule_pause\` — Pause, resume, or skip N runs
- \`bakin_exec_schedule_delete\` — Remove a job
- \`bakin_exec_schedule_briefing\` — Today's schedule summary (for daily standup)

### When to Use Scheduling vs One-Off Tasks
- **Recurring work** (daily posts, weekly reports, periodic checks) → \`bakin_exec_schedule_create\`
- **One-time deliverables** → \`bakin_exec_tasks_create\``,
  },

  {
    blockId: 'asset-rules',
    contentFn: (agentId: string) => `## Bakin Asset Rules

> Auto-managed by \`bakin doctor\`. Do not edit this block manually.

All created content (images, video, audio, text, plans, data) MUST go to the assets directory. Use the Bakin skill for full conventions, but here's the minimum:

1. **Discover paths via mcporter:** \`mcporter call bakin-${agentId}.bakin_exec_get_paths\`
2. **Organize by task:** \`\$ASSETS_DIR/<task-id>/filename.ext\`
   - **No task?** Write to \`\$ASSETS_DIR/_unlinked/\` — NEVER place files directly in the type root (e.g. \`assets/text/file.md\` is WRONG, use \`assets/text/_unlinked/file.md\`)
   - **Shared/reusable?** Write to \`\$ASSETS_DIR/library/\`
3. **Write sidecar FIRST, then the asset.** Sidecar filename = full asset filename + \`.meta.json\` (e.g. \`20260323-hero.png.meta.json\`, NOT \`hero.meta.json\`)
4. **Sidecar fields — use these EXACT names:**
   - \`agent\` (required, string — NOT \`author\`), \`taskId\` (required, string or null), \`created\` (required, ISO 8601 — NOT \`createdAt\`)
   - Optional: \`tool\`, \`description\`, \`tags\` (string[]), \`originalFilename\`
   - Do NOT add custom fields (e.g. \`prompt\`, \`resolution\`)
5. **Version with timestamps:** \`20260323-hero-image.png\` for revisions.`,
  },
]

/**
 * Apply all managed blocks. Called by both doctor and the CLI.
 */
export function applyAllManagedBlocks(autoFix: boolean): DiagnosticResult[] {
  const results: DiagnosticResult[] = []
  for (const block of MANAGED_BLOCKS) {
    results.push(...checkManagedBlock(block, autoFix))
  }
  return results
}

// ---------------------------------------------------------------------------
// Workflow health checks
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

/**
 * Run all health checks with auto-fix for safe issues.
 * Notifies the main agent via OpenClaw about issues that need human judgment.
 */

/**
 * Plugin-shipped OpenClaw skills (S-B): surface install state + drift.
 * Never auto-installs — points the user at `bakin install plugin-assets`.
 */
async function checkPluginAssets(): Promise<DiagnosticResult[]> {
  try {
    const result = await pluginAssetsComponent.check()
    if (result.status === 'ok') {
      return [ok('plugin-assets', result.message)]
    }
    const reminder = result.remediation ?? 'Run `bakin install plugin-assets` to apply.'
    return [warn('plugin-assets', `${result.message} — ${reminder}`)]
  } catch (err) {
    return [warn('plugin-assets', `plugin-assets check failed: ${err}`)]
  }
}

export async function runDiagnostics(
  contentDir: string,
  projectRoot: string
): Promise<DiagnosticResult[]> {
  const settings = getSettings()

  // Gate: if the machine has never been through first-run onboarding and
  // the config says to enforce it, return a single actionable error and
  // skip all the normal checks. Keeps doctor quiet on a fresh machine
  // and points the user at `bakin onboard` instead of drowning them in
  // unrelated errors about missing personas, gateway down, etc.
  if (settings.doctor.requireOnboard && !isOnboarded()) {
    return [{
      check: 'onboarded',
      status: 'error',
      message: 'Bakin is not onboarded on this machine. Run `bakin onboard` to complete first-run setup.',
      autoFixable: false,
    }]
  }

  const autoFix = settings.doctor.autoFixSkill // reuse as general autoFix flag

  const results: DiagnosticResult[] = []

  // Sync checks (fast, some auto-fixable)
  results.push(...checkContentDir())
  results.push(...checkAndSyncSkill(projectRoot, autoFix))
  results.push(...await checkOrchestratorRules(autoFix))
  results.push(...applyAllManagedBlocks(autoFix))
  // Migrated checks (live in their owner plugins, picked up via the
  // plugin-check loop at the end of this function):
  //   workflows: workflow-skills / workflow-definitions / workflow-instances (#137)
  //   team: agent-roster / personas / agent-assets (#139 C1)
  //   tasks: taskboard / task-consistency / order-integrity (#139 C2)
  //   assets: assets (#139 C3)
  //   schedule: schedule-sync (#139 C4)
  results.push(...checkMcporter(Number(process.env.PORT || 3737), autoFix))
  results.push(...checkService(projectRoot))

  // Async checks (network, not auto-fixable) — run in parallel
  const [gatewayResults, antflyResults, searchTableResults, pluginAssetsResults] = await Promise.all([
    checkGateway(),
    checkAntfly(),
    checkSearchTables(),
    checkPluginAssets(),
  ])
  results.push(...gatewayResults, ...antflyResults, ...searchTableResults, ...pluginAssetsResults)

  // Plugin-contributed health checks (#137). Results appended to the same
  // list as builtins; the UI groups by status so ordering doesn't matter.
  results.push(...await runPluginHealthChecks())

  // Summarize
  const errors = results.filter(r => r.status === 'error').length
  const warnings = results.filter(r => r.status === 'warn').length
  const fixes = results.filter(r => r.status === 'fixed').length

  if (errors > 0 || warnings > 0) {
    log.warn('Doctor found issues', { errors, warnings, fixes })
  } else {
    log.info('Doctor: all checks passed', { fixes })
  }

  appendAudit(contentDir, 'doctor.run', 'system', {
    total: results.length,
    errors,
    warnings,
    fixes,
  })

  // Notify the main agent about things we can't auto-fix
  await notifyUnfixableIssues(results)

  // Cache results for lightweight reads (e.g. health plugin polling)
  lastDiagnosticResults = results
  lastDiagnosticTime = Date.now()

  return results
}

/**
 * Return the most recent diagnostic results without re-running checks.
 * Returns null if diagnostics have never run.
 */
export function getLastResults(): { results: DiagnosticResult[]; timestamp: number } | null {
  if (!lastDiagnosticResults) return null
  return { results: lastDiagnosticResults, timestamp: lastDiagnosticTime }
}

// ---------------------------------------------------------------------------
// Cron
// ---------------------------------------------------------------------------

export function start(contentDir: string, projectRoot: string): void {
  const settings = getSettings()

  // Run immediately on startup
  runDiagnostics(contentDir, projectRoot).catch(err => {
    log.error('Doctor startup check failed', err)
  })

  // Then run on interval
  doctorTimer = setInterval(() => {
    // Clear notification cache each cycle so recurring issues get re-reported
    // (but not within the same cycle)
    notifiedIssues.clear()
    runDiagnostics(contentDir, projectRoot).catch(err => {
      log.error('Doctor periodic check failed', err)
    })
  }, settings.doctor.intervalMs)

  log.info('Doctor started', { intervalMs: settings.doctor.intervalMs })
}

export function stop(): void {
  if (doctorTimer) {
    clearInterval(doctorTimer)
    doctorTimer = null
    log.info('Doctor stopped')
  }
}
