/**
 * Static asset + SPA fallback server for the Bakin host bundle.
 *
 * Serves:
 *   /_app/<name>      → packages/host/dist/<name>  (main.js, main.css, *.map)
 *                       (NOT /assets/* — that's the assets plugin's page
 *                       namespace; client routes like /assets/<assetId> must
 *                       reach the SPA fallback on hard refresh)
 *   /vendor/<name>    → packages/host/public/vendor/<name>  (react, sdk, etc.)
 *   /globals.css      → packages/sdk/styles.css
 *   /favicon.ico      → packages/host/public/favicon.ico (404 ok if absent)
 *   anything else     → packages/host/public/index.html  (SPA fallback;
 *                        TanStack Router handles client-side routing)
 *
 * API paths (`/api/*`) and MCP (`/mcp/*`) are matched earlier in server.ts
 * and never reach this handler.
 *
 * Asset resolution order:
 *   1. EMBEDDED_ASSETS map (generated by scripts/generate-embedded-assets.ts)
 *      — one path per file, imported via `type: 'file'` so Bun's --compile
 *      embeds bytes into the binary at build time. Dev runs hit the same
 *      map but the values are absolute on-disk paths, so nothing changes.
 *   2. Disk fallback under process.cwd()/packages/host/{dist,public}, plus
 *      packages/sdk/styles.css — kept so freshly regenerated assets work
 *      without re-running the embedded-assets generator during inner loops.
 */
import type { IncomingMessage, ServerResponse } from 'http'
import { createReadStream, existsSync, readFileSync, statSync } from 'fs'
import { join, extname, resolve } from 'path'

import { EMBEDDED_ASSETS } from './_embedded-assets'
import {
  canCompressResponse,
  writeEncodedResponseBody,
} from './compression'

// Repo-root-relative. server.ts is always invoked from the repo root so
// process.cwd() is stable in dev. In the compiled binary, EMBEDDED_ASSETS
// covers everything these dirs would have held.
const DIST_DIR = resolve(process.cwd(), 'packages/host/dist')
const PUBLIC_DIR = resolve(process.cwd(), 'packages/host/public')
const SDK_STYLES_PATH = resolve(process.cwd(), 'packages/sdk/styles.css')

const DEV_CLIENT_TAG = '<script type="module" src="/__bakin-dev/client.js"></script>'

/**
 * Inject the dev-client script before `</body>` when BAKIN_DEV=1, else
 * return the input bytes unchanged (reference equality preserved). Exported
 * so tests can exercise both branches without spinning up a server.
 */
export function transformIndexHtmlForDev(bytes: Buffer): Buffer {
  if (process.env.BAKIN_DEV !== '1') return bytes
  const html = bytes.toString('utf-8')
  const idx = html.toLowerCase().lastIndexOf('</body>')
  if (idx === -1) {
    console.warn('[bakin-dev] index.html has no </body> — skipping dev-client injection')
    return bytes
  }
  const injected = html.slice(0, idx) + DEV_CLIENT_TAG + html.slice(idx)
  return Buffer.from(injected, 'utf-8')
}

const MIME: Record<string, string> = {
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.ico': 'image/x-icon',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.json': 'application/json; charset=utf-8',
}

function mimeFor(path: string): string {
  return MIME[extname(path).toLowerCase()] ?? 'application/octet-stream'
}

/**
 * Pick the Cache-Control header for a response. In dev we force no-store on
 * every asset — the watcher rebuilds main.js / client.js / vendor bundles
 * in place, and location.reload() won't pick up the new bytes if the
 * browser's HTTP cache says the old ones are still fresh. In production
 * the binary's assets never change at runtime, so the 5-minute cache is
 * fine and cuts the number of HEAD requests the browser makes. Exported
 * for unit-testing.
 */
export function cacheControlFor(urlOrPath: string, status: number): string {
  if (status !== 200) return 'public, max-age=300'
  if (process.env.BAKIN_DEV === '1') return 'no-store'
  if (urlOrPath.endsWith('.html')) return 'no-cache'
  return 'public, max-age=300'
}

async function sendEmbedded(req: IncomingMessage, res: ServerResponse, urlPath: string, status = 200): Promise<boolean> {
  const embeddedPath = EMBEDDED_ASSETS.get(urlPath)
  if (!embeddedPath) return false
  try {
    const file = Bun.file(embeddedPath)
    if (!(await file.exists())) return false
    const bytes = new Uint8Array(await file.arrayBuffer())
    await writeEncodedResponseBody(req, res, status, {
      'Content-Type': mimeFor(urlPath),
      'Content-Length': String(bytes.length),
      'Cache-Control': cacheControlFor(urlPath, status),
    }, bytes)
    return true
  } catch {
    return false
  }
}

async function sendDiskFile(req: IncomingMessage, res: ServerResponse, path: string, status = 200): Promise<boolean> {
  if (!existsSync(path)) return false
  const stat = statSync(path)
  if (!stat.isFile()) return false
  const headers = {
    'Content-Type': mimeFor(path),
    'Content-Length': stat.size,
    'Cache-Control': cacheControlFor(path, status),
  }
  if (canCompressResponse(req, status, headers, stat.size)) {
    await writeEncodedResponseBody(req, res, status, headers, readFileSync(path))
    return true
  }
  res.writeHead(status, headers)
  createReadStream(path).pipe(res)
  return true
}

/**
 * Try to serve a static asset or fall back to index.html. Returns true if
 * the request was handled (response started); false otherwise.
 */
export async function serveHostClient(req: IncomingMessage, res: ServerResponse, url: URL): Promise<boolean> {
  // Only GET/HEAD make sense for static serving.
  if (req.method !== 'GET' && req.method !== 'HEAD') return false

  const pathname = url.pathname
  if (pathname.includes('..')) {
    res.writeHead(400, { 'Content-Type': 'text/plain' })
    res.end('Bad request')
    return true
  }

  // Dev-client bundle — served from disk when BAKIN_DEV=1, 404 otherwise.
  // The unconditional 404 when unset keeps production from falling through
  // to the SPA fallback (which would return index.html with a 200 for an
  // asset request). scripts/dev.ts builds this to packages/host/public/__bakin-dev/.
  if (pathname.startsWith('/__bakin-dev/')) {
    if (process.env.BAKIN_DEV !== '1') {
      res.writeHead(404, { 'Content-Type': 'text/plain' })
      res.end('Not found')
      return true
    }
    const rel = pathname.slice('/__bakin-dev/'.length)
    if (await sendDiskFile(req, res, join(PUBLIC_DIR, '__bakin-dev', rel))) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  // Exact-match lookup for anything embedded first (assets, vendor, public).
  if (await sendEmbedded(req, res, pathname)) return true

  // Disk fallback for dev — mirrors the old resolution logic.
  if (pathname.startsWith('/_app/')) {
    const rel = pathname.slice('/_app/'.length)
    if (await sendDiskFile(req, res, join(DIST_DIR, rel))) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  if (pathname.startsWith('/vendor/')) {
    const rel = pathname.slice('/vendor/'.length)
    if (await sendDiskFile(req, res, join(PUBLIC_DIR, 'vendor', rel))) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  if (pathname === '/globals.css') {
    if (await sendDiskFile(req, res, SDK_STYLES_PATH)) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  if (pathname === '/favicon.ico') {
    if (await sendDiskFile(req, res, join(PUBLIC_DIR, 'favicon.ico'))) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  // SPA fallback — every other GET returns index.html so TanStack Router
  // handles the route client-side. In dev the bytes are transformed to
  // inject the dev-client script; in prod they pass through unchanged.
  const indexBytes = await loadIndexHtml()
  if (indexBytes) {
    const body = transformIndexHtmlForDev(indexBytes)
    await writeEncodedResponseBody(req, res, 200, {
      'Content-Type': 'text/html; charset=utf-8',
      'Content-Length': String(body.length),
      'Cache-Control': 'no-cache',
    }, body)
    return true
  }

  res.writeHead(500, { 'Content-Type': 'text/plain' })
  res.end('Host bundle not built — run `bun run build:host`')
  return true
}

async function loadIndexHtml(): Promise<Buffer | null> {
  const embedded = EMBEDDED_ASSETS.get('/index.html')
  if (embedded) {
    try {
      const file = Bun.file(embedded)
      if (await file.exists()) {
        return Buffer.from(await file.arrayBuffer())
      }
    } catch { /* fall through to disk */ }
  }
  const diskPath = join(PUBLIC_DIR, 'index.html')
  if (existsSync(diskPath)) {
    return readFileSync(diskPath)
  }
  return null
}
