/**
 * Static asset + SPA fallback server for the Bakin host bundle.
 *
 * Serves:
 *   /assets/<name>    → packages/host/dist/<name>  (main.js, main.css, *.map)
 *   /vendor/<name>    → packages/host/public/vendor/<name>  (react, sdk, etc.)
 *   /globals.css      → packages/host/public/globals.css
 *   /favicon.ico      → packages/host/public/favicon.ico (404 ok if absent)
 *   anything else     → packages/host/public/index.html  (SPA fallback;
 *                        TanStack Router handles client-side routing)
 *
 * API paths (`/api/*`) and MCP (`/mcp/*`) are matched earlier in server.ts
 * and never reach this handler.
 *
 * Asset resolution order:
 *   1. EMBEDDED_ASSETS map (generated by scripts/generate-embedded-assets.ts)
 *      — one path per file, imported via `type: 'file'` so Bun's --compile
 *      embeds bytes into the binary at build time. Dev runs hit the same
 *      map but the values are absolute on-disk paths, so nothing changes.
 *   2. Disk fallback under process.cwd()/packages/host/{dist,public} — kept
 *      so a freshly regenerated dist/ works without re-running the
 *      embedded-assets generator during inner dev loops.
 */
import type { IncomingMessage, ServerResponse } from 'http'
import { createReadStream, existsSync, statSync } from 'fs'
import { join, extname, resolve } from 'path'

import { EMBEDDED_ASSETS } from './_embedded-assets'

// Repo-root-relative. server.ts is always invoked from the repo root so
// process.cwd() is stable in dev. In the compiled binary, EMBEDDED_ASSETS
// covers everything these dirs would have held.
const DIST_DIR = resolve(process.cwd(), 'packages/host/dist')
const PUBLIC_DIR = resolve(process.cwd(), 'packages/host/public')

const MIME: Record<string, string> = {
  '.js': 'application/javascript; charset=utf-8',
  '.mjs': 'application/javascript; charset=utf-8',
  '.map': 'application/json; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.ico': 'image/x-icon',
  '.png': 'image/png',
  '.svg': 'image/svg+xml',
  '.woff': 'font/woff',
  '.woff2': 'font/woff2',
  '.json': 'application/json; charset=utf-8',
}

function mimeFor(path: string): string {
  return MIME[extname(path).toLowerCase()] ?? 'application/octet-stream'
}

async function sendEmbedded(res: ServerResponse, urlPath: string, status = 200): Promise<boolean> {
  const embeddedPath = EMBEDDED_ASSETS.get(urlPath)
  if (!embeddedPath) return false
  try {
    const file = Bun.file(embeddedPath)
    if (!(await file.exists())) return false
    const bytes = new Uint8Array(await file.arrayBuffer())
    res.writeHead(status, {
      'Content-Type': mimeFor(urlPath),
      'Content-Length': String(bytes.length),
      'Cache-Control': status === 200 && urlPath.endsWith('.html') ? 'no-cache' : 'public, max-age=300',
    })
    res.end(bytes)
    return true
  } catch {
    return false
  }
}

function sendDiskFile(res: ServerResponse, path: string, status = 200): boolean {
  if (!existsSync(path)) return false
  const stat = statSync(path)
  if (!stat.isFile()) return false
  res.writeHead(status, {
    'Content-Type': mimeFor(path),
    'Content-Length': stat.size,
    'Cache-Control': status === 200 && path.endsWith('.html') ? 'no-cache' : 'public, max-age=300',
  })
  createReadStream(path).pipe(res)
  return true
}

/**
 * Try to serve a static asset or fall back to index.html. Returns true if
 * the request was handled (response started); false otherwise.
 */
export async function serveHostClient(req: IncomingMessage, res: ServerResponse, url: URL): Promise<boolean> {
  // Only GET/HEAD make sense for static serving.
  if (req.method !== 'GET' && req.method !== 'HEAD') return false

  const pathname = url.pathname
  if (pathname.includes('..')) {
    res.writeHead(400, { 'Content-Type': 'text/plain' })
    res.end('Bad request')
    return true
  }

  // Exact-match lookup for anything embedded first (assets, vendor, public).
  if (await sendEmbedded(res, pathname)) return true

  // Disk fallback for dev — mirrors the old resolution logic.
  if (pathname.startsWith('/assets/')) {
    const rel = pathname.slice('/assets/'.length)
    if (sendDiskFile(res, join(DIST_DIR, rel))) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  if (pathname.startsWith('/vendor/')) {
    const rel = pathname.slice('/vendor/'.length)
    if (sendDiskFile(res, join(PUBLIC_DIR, 'vendor', rel))) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  if (pathname === '/globals.css' || pathname === '/favicon.ico') {
    if (sendDiskFile(res, join(PUBLIC_DIR, pathname.slice(1)))) return true
    res.writeHead(404, { 'Content-Type': 'text/plain' })
    res.end('Not found')
    return true
  }

  // SPA fallback — every other GET returns index.html so TanStack Router
  // handles the route client-side.
  if (await sendEmbedded(res, '/index.html')) return true
  if (sendDiskFile(res, join(PUBLIC_DIR, 'index.html'))) return true

  res.writeHead(500, { 'Content-Type': 'text/plain' })
  res.end('Host bundle not built — run `bun run build:host`')
  return true
}
