import { expect, test } from 'playwright/test'

test('Select summarizes multiple values, submits each value and resets deliberately', async ({ page }) => {
  await page.goto('/iframe.html?id=components-primitives-select--multiple-selection&viewMode=story')
  const trigger = page.getByRole('combobox', { name: 'Allowed runtimes' })
  await expect(trigger).toHaveText('Pi +2 more')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  expect(await page.locator('form').evaluate(form => new FormData(form as HTMLFormElement).getAll('runtimes'))).toEqual(['pi', 'openclaw', 'managed'])
  await page.getByRole('button', { name: 'Reset runtimes' }).click()
  await expect(trigger).toHaveText('Pi +1 more')
  await page.setViewportSize({ width: 320, height: 800 })
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('listbox')).toBeVisible()
  const popup = page.locator('[data-slot=select-content]')
  const bounds = await popup.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})

test('Combobox chips and filtering work inside a narrow Dialog with predictable focus return', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto('/iframe.html?id=components-primitives-combobox--overlay-fixture&viewMode=story')
  await page.getByRole('button', { name: 'Configure runtime' }).click()
  const input = page.getByRole('combobox', { name: 'Dialog runtimes' })
  await input.fill('Managed')
  await expect(page.getByRole('option', { name: /^Managed/ })).toBeVisible()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: /^Remove Managed/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await page.getByRole('button', { name: 'Remove Pi', exact: true }).click()
  await expect(input).toBeFocused()
  await input.fill('No matching entry')
  await expect(page.getByText('No runtimes found.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('button', { name: /^Remove Managed/ })).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Configure runtime' })).toBeFocused()
})


test('Combobox compact mode keeps object values, keyboard removal and the editable query', async ({ page }) => {
  await page.goto('/iframe.html?id=components-primitives-combobox--compact-and-object-values&viewMode=story')
  await expect(page.getByLabel('Submitted runtime IDs')).toHaveText('pi, claw')
  await expect(page.getByRole('button', { name: 'Remove OpenClaw' })).toBeVisible()
  const input = page.getByRole('combobox', { name: 'Object runtimes' })
  await input.focus()
  await page.keyboard.press('Backspace')
  await expect(page.getByRole('button', { name: 'Remove OpenClaw' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Show compact summary' }).click()
  await input.fill('Managed')
  await expect(page.getByRole('option', { name: /^Managed/ })).toBeVisible()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(page.getByText('Pi +1 more', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Submit runtimes' }).click()
  await expect(page.getByLabel('Submitted runtime IDs')).toHaveText('pi, hosted')
  await page.getByRole('button', { name: 'Show chips' }).click()
  await page.setViewportSize({ width: 320, height: 800 })
  await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await expect(page.getByRole('button', { name: /^Remove Managed/ })).toBeVisible()
})


test('async results ignore older queries and retry is reachable by keyboard without losing selection', async ({ page }) => {
  await page.goto('/iframe.html?id=components-primitives-combobox--async-fixture&viewMode=story')
  const input = page.getByRole('combobox', { name: 'Remote runtime' })
  await expect(page.getByRole('status')).toHaveText('3 runtimes available.')
  const clockStart = new Date('2026-09-22T00:00:00Z')
  // Install before the pause target so protocol latency cannot put it in the past.
  await page.clock.install({ time: new Date(clockStart.getTime() - 60_000) })
  await page.clock.pauseAt(clockStart)
  await input.fill('slow')
  await expect(page.getByRole('status')).toHaveText('Loading runtimes…')
  await input.fill('fast')
  await page.clock.runFor(100)
  await expect(page.getByRole('option', { name: /OpenClaw/ })).toBeVisible()
  // Resolve the older request deterministically after the newer result.
  await page.clock.runFor(400)
  await expect(page.getByRole('option', { name: /OpenClaw/ })).toBeVisible()
  await expect(page.getByRole('option', { name: /^Pi/ })).toHaveCount(0)
  await expect(page.getByText('Selected runtime: Pi', { exact: true })).toBeVisible()
  await input.fill('error')
  await page.clock.runFor(100)
  const retry = page.getByRole('button', { name: 'Retry runtime search' })
  await expect(retry).toBeVisible()
  await input.focus()
  for (let index = 0; index < 5 && !(await retry.evaluate(el => el === document.activeElement)); index++) await page.keyboard.press('Tab')
  await expect(retry).toBeFocused()
  await page.keyboard.press('Enter')
  await page.clock.runFor(100)
  await expect(page.getByRole('status')).toHaveText('3 runtimes available.')
  await expect(page.getByText('Selected runtime: Pi', { exact: true })).toBeVisible()
})
