import { expect, test } from 'playwright/test'

test('mixed form serializes IDs and arrays, resets controls and protects IME composition', async ({ page }) => {
  await page.goto('/iframe.html?id=components-forms-field-and-form-composition--foundation-controls&viewMode=story')
  await expect(page.locator('[role=status]')).toHaveText('Reset to defaults')
  const form = page.getByRole('form', { name: 'Foundation form' })
  expect(await form.evaluate(element => {
    const data = new FormData(element as HTMLFormElement)
    return { title: data.get('title'), channels: data.getAll('channels'), owner: data.get('owner') }
  })).toEqual({ title: 'Workflow', channels: ['email', 'chat'], owner: 'maya' })
  const owner = page.getByRole('combobox', { name: 'Workflow owner' })
  await owner.fill('Jules')
  await page.keyboard.press('ArrowDown')
  await owner.dispatchEvent('compositionstart', { data: '' })
  await owner.dispatchEvent('keydown', { key: 'Enter', code: 'Enter', keyCode: 229, isComposing: true })
  await expect(page.locator('[role=status]')).toHaveText('Reset to defaults')
  expect(await form.evaluate(element => new FormData(element as HTMLFormElement).get('owner'))).toBe('maya')
  await owner.dispatchEvent('compositionend', { data: 'Jules' })
  await page.keyboard.press('Enter')
  expect(await form.evaluate(element => new FormData(element as HTMLFormElement).get('owner'))).toBe('jules')
  await page.getByRole('button', { name: 'Reset form' }).click()
  await expect(owner).toHaveValue('Maya')
  await page.getByRole('button', { name: 'Save workflow' }).click()
  await expect(page.getByRole('status')).toHaveText('Saved Workflow; email, chat; maya')
})

test('async selection retry remains keyboard-accessible inside Drawer', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto('/iframe.html?id=recipes-form-in-a-drawer--searchable-controls&viewMode=story')
  const opener = page.getByRole('button', { name: 'Configure selections' })
  await opener.click()
  const input = page.getByRole('combobox', { name: 'Remote runtime' })
  await input.fill('error')
  const retry = page.getByRole('button', { name: 'Retry runtime search' })
  await expect(retry).toBeVisible()
  for (let i = 0; i < 5 && !(await retry.evaluate(el => el === document.activeElement)); i++) await page.keyboard.press('Tab')
  await expect(retry).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('status')).toHaveText('3 runtimes available.')
  await expect(page.getByRole('dialog', { name: 'Selection editor' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await page.getByRole('button', { name: 'Close panel' }).click()
  await expect(opener).toBeFocused()
})
