import { expect, test } from 'playwright/test'

test('Select summarizes multiple values, submits each value and resets deliberately', async ({ page }) => {
  await page.goto('/iframe.html?id=components-primitives-select--multiple-selection&viewMode=story')
  const trigger = page.getByRole('combobox', { name: 'Allowed runtimes' })
  await expect(trigger).toHaveText('Pi +2 more')
  await expect(page.getByRole('listbox')).toHaveCount(0)
  expect(await page.locator('form').evaluate(form => new FormData(form as HTMLFormElement).getAll('runtimes'))).toEqual(['pi', 'openclaw', 'managed'])
  await page.getByRole('button', { name: 'Reset runtimes' }).click()
  await expect(trigger).toHaveText('Pi +1 more')
  await page.setViewportSize({ width: 320, height: 800 })
  await trigger.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('listbox')).toBeVisible()
  const popup = page.locator('[data-slot=select-content]')
  const bounds = await popup.boundingBox()
  expect(bounds!.x).toBeGreaterThanOrEqual(0)
  expect(bounds!.x + bounds!.width).toBeLessThanOrEqual(320)
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
})

test('Combobox chips and filtering work inside a narrow Dialog with predictable focus return', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 800 })
  await page.goto('/iframe.html?id=components-primitives-combobox--overlay-fixture&viewMode=story')
  await page.getByRole('button', { name: 'Configure runtime' }).click()
  const input = page.getByRole('combobox', { name: 'Dialog runtimes' })
  await input.fill('Managed')
  await expect(page.getByRole('option', { name: /^Managed/ })).toBeVisible()
  await page.keyboard.press('ArrowDown')
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: /^Remove Managed/ })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320)
  await page.getByRole('button', { name: 'Remove Pi', exact: true }).click()
  await expect(input).toBeFocused()
  await input.fill('No matching entry')
  await expect(page.getByText('No runtimes found.')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Configure runtime' })).toBeFocused()
})
